-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."circles" add column "deleted_at" time without time zone
--  null;
