-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."distributions" add column "gift_amount" numeric
--  not null default '0';
