-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."reputation_scores" add column "colinks_engagement_score" integer
--  null default '0';
