-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."circle_api_keys" add column "read_discord" boolean
--  not null default 'false';
