-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contributions" add column "private_stream" boolean
--  not null default 'false';
