/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgAlertSolid = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m8.692 2.124 6.546 10.638A.813.813 0 0 1 14.546 14H1.454a.812.812 0 0 1-.692-1.238L7.308 2.124a.812.812 0 0 1 1.384 0Zm-.17 8.132.11-4.074H7.368l.114 4.074h1.04Zm-1.003 1.619a.664.664 0 0 0 .482.199c.122 0 .233-.03.336-.091a.734.734 0 0 0 .247-.247.652.652 0 0 0-.108-.821.66.66 0 0 0-.475-.2.664.664 0 0 0-.482.2.637.637 0 0 0-.2.477.65.65 0 0 0 .2.483Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgAlertSolid;
