/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgArbitrum = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <path
      d="m16.93 18.432-1.586 4.248a.493.493 0 0 0 0 .366l2.724 7.311 3.153-1.78-3.782-10.145a.271.271 0 0 0-.509 0ZM20.103 11.284a.272.272 0 0 0-.509 0l-1.586 4.248a.495.495 0 0 0 0 .367l4.465 11.971 3.153-1.78-5.523-14.806Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.75 0 0 .75 1.125 0)"
    />
    <path
      d="M14.5 1.983c.08 0 .154.02.228.059L26.751 8.83c.14.078.227.222.227.379v13.575a.438.438 0 0 1-.227.38l-12.023 6.794a.478.478 0 0 1-.456 0L2.256 23.17a.434.434 0 0 1-.228-.379V9.209c0-.157.087-.301.228-.379l12.023-6.788a.449.449 0 0 1 .221-.059ZM14.5 0c-.428 0-.857.111-1.238.327L1.238 7.115A2.414 2.414 0 0 0 0 9.209v13.575c0 .864.475 1.669 1.238 2.101l12.024 6.788a2.516 2.516 0 0 0 2.477 0l12.023-6.788A2.405 2.405 0 0 0 29 22.784V9.209c0-.864-.475-1.669-1.238-2.101L15.745.327A2.562 2.562 0 0 0 14.5 0Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.75 0 0 .75 1.125 0)"
    />
    <path
      d="m6.555 27.883 1.104-2.958 2.223 1.806-2.075 1.859-1.252-.707ZM13.489 8.24h-3.046a.536.536 0 0 0-.509.347L3.4 26.103l3.153 1.78L13.75 8.594a.268.268 0 0 0-.261-.354Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.75 0 0 .75 1.125 0)"
    />
    <path
      d="M18.824 8.24h-3.046a.535.535 0 0 0-.509.347L7.805 28.59l3.153 1.78 8.12-21.77a.267.267 0 0 0-.254-.36Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.75 0 0 .75 1.125 0)"
    />
  </SvgIcon>
);
export default SvgArbitrum;
