/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgArrowUpRightDots = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <g transform="matrix(.04167 0 0 .04167 0 1.333)">
      <clipPath id="arrow-up-right-dots_svg__a">
        <path d="M0 0h576v512H0z" />
      </clipPath>
      <g clipPath="url(#arrow-up-right-dots_svg__a)">
        <path
          d="M128 24c0 13.3 10.7 24 24 24h86.1L7 279c-9.4 9.4-9.4 24.6 0 33.9 9.4 9.3 24.6 9.4 33.9 0l231-231V168c0 13.3 10.7 24 24 24s24-10.7 24-24V24c0-13.3-10.7-24-24-24H152c-13.3 0-24 10.7-24 24Zm448 56c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48ZM448 208c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm-48 176c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Zm48 80c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm128 0c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm-304-80c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Zm48 80c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm-176 48c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Zm432-176c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm-48-80c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Z"
          style={{
            fillRule: 'nonzero',
          }}
        />
      </g>
    </g>
  </SvgIcon>
);
export default SvgArrowUpRightDots;
