/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgAuroraLogo = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#70D44B"
      d="M12 1.833a2.653 2.653 0 0 1 2.385 1.474l7.5 15a2.667 2.667 0 0 1-2.385 3.86h-15a2.667 2.667 0 0 1-2.385-3.86l7.5-15A2.653 2.653 0 0 1 12 1.833ZM12 0a4.5 4.5 0 0 0-4.025 2.487l-7.5 15A4.5 4.5 0 0 0 4.5 24h15a4.5 4.5 0 0 0 4.024-6.513l-7.5-15A4.5 4.5 0 0 0 12 0Z"
    />
  </SvgIcon>
);
export default SvgAuroraLogo;
