/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgBadge = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <g clipPath="url(#badge_svg__a)" fill="#000">
      <path d="M8 10.667c-2.933 0-5.333-2.4-5.333-5.334C2.667 2.4 5.067 0 8 0c2.933 0 5.333 2.4 5.333 5.333 0 2.934-2.4 5.334-5.333 5.334Zm0-9.334c-2.2 0-4 1.8-4 4s1.8 4 4 4 4-1.8 4-4-1.8-4-4-4Z" />
      <path d="M10.667 16c-.134 0-.2 0-.267-.067l-2.4-1.2-2.4 1.2c-.2.134-.467.067-.667 0-.133-.133-.266-.4-.266-.6v-6c0-.4.266-.666.666-.666S6 8.933 6 9.333v4.934l1.733-.867c.2-.067.4-.067.6 0l1.734.867V9.333c0-.4.266-.666.666-.666s.667.266.667.666v6c0 .2-.133.467-.333.6-.134 0-.267.067-.4.067Z" />
    </g>
    <defs>
      <clipPath id="badge_svg__a">
        <path fill="#fff" d="M0 0h16v16H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgBadge;
