/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgBadgeFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      d="m12 .289 2.568 2.13 3.289-.561 1.158 3.128 3.128 1.158-.56 3.289L23.712 12l-2.13 2.568.56 3.288-3.128 1.159-1.158 3.128-3.289-.561-2.567 2.13-2.568-2.13-3.288.56-1.159-3.127-3.128-1.159.56-3.288L.29 12l2.13-2.567-.56-3.289 3.127-1.158 1.159-3.128 3.288.56 2.568-2.13Z"
    />
  </SvgIcon>
);
export default SvgBadgeFill;
