/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgBadge = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      stroke="#070707"
      strokeWidth={2}
      d="m9.733 3.538 1.695 1.184.573.4.573-.4 1.694-1.184.876 1.873.296.633.696-.06 2.06-.179-.179 2.06-.06.696.633.296 1.874.876-1.185 1.694-.4.573.4.573 1.185 1.695-1.874.875-.633.296.06.696.179 2.06-2.06-.178-.696-.06-.296.633-.876 1.873-1.694-1.185-.573-.4-.573.4-1.695 1.185-.875-1.873-.296-.634-.696.06-2.06.18.178-2.06.06-.697-.632-.296-1.874-.875 1.185-1.695.4-.573-.4-.573-1.185-1.694 1.874-.876.633-.296-.06-.696-.18-2.06 2.06.179.697.06.296-.633.875-1.873Z"
    />
  </SvgIcon>
);
export default SvgBadge;
