/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgBoltFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M17.224 3.742c.246-.535.062-1.16-.442-1.503a1.405 1.405 0 0 0-1.662.07l-10.664 8.75c-.417.343-.567.894-.371 1.378.196.485.696.813 1.25.813H9.98l-3.204 7.008c-.246.535-.062 1.16.442 1.503a1.405 1.405 0 0 0 1.662-.07l10.664-8.75c.417-.343.567-.894.371-1.378-.196-.485-.692-.809-1.25-.809H14.02l3.204-7.012Z"
    />
  </SvgIcon>
);
export default SvgBoltFill;
