/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgBullseye = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="bullseye_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#bullseye_svg__a)">
        <g transform="matrix(.34995 0 0 .31404 190.107 167.501)">
          <clipPath id="bullseye_svg__b">
            <path d="M0 0h512v512H0z" />
          </clipPath>
          <g clipPath="url(#bullseye_svg__b)">
            <path
              d="M480 256c0-122.883-101.117-224-224-224S32 133.117 32 256s101.117 224 224 224 224-101.117 224-224ZM0 256C0 115.563 115.563 0 256 0s256 115.563 256 256-115.563 256-256 256S0 396.437 0 256Zm256 128c70.219 0 128-57.781 128-128s-57.781-128-128-128-128 57.781-128 128 57.781 128 128 128Zm0-288c87.773 0 160 72.227 160 160s-72.227 160-160 160S96 343.773 96 256 168.227 96 256 96Zm0 192c17.555 0 32-14.445 32-32s-14.445-32-32-32-32 14.445-32 32 14.445 32 32 32Zm0-96c35.109 0 64 28.891 64 64s-28.891 64-64 64-64-28.891-64-64 28.891-64 64-64Z"
              style={{
                fillRule: 'nonzero',
              }}
            />
          </g>
        </g>
      </g>
    </g>
  </SvgIcon>
);
export default SvgBullseye;
