/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgBullseyeThin = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="bullseye-thin_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#bullseye-thin_svg__a)">
        <g transform="matrix(.34995 0 0 .31404 190.107 167.501)">
          <clipPath id="bullseye-thin_svg__b">
            <path d="M0 0h512v512H0z" />
          </clipPath>
          <g clipPath="url(#bullseye-thin_svg__b)">
            <path
              d="M256 16c131.66 0 240 108.34 240 240S387.66 496 256 496 16 387.66 16 256 124.34 16 256 16Zm0 496c140.437 0 256-115.563 256-256S396.437 0 256 0 0 115.563 0 256s115.563 256 256 256Zm0-408c83.385 0 152 68.615 152 152s-68.615 152-152 152-152-68.615-152-152 68.615-152 152-152Zm0 320c92.162 0 168-75.838 168-168S348.162 88 256 88 88 163.838 88 256s75.838 168 168 168Zm-56-168c0-30.721 25.279-56 56-56s56 25.279 56 56-25.279 56-56 56-56-25.279-56-56Zm128 0c0-39.498-32.502-72-72-72s-72 32.502-72 72 32.502 72 72 72 72-32.502 72-72Z"
              style={{
                fillRule: 'nonzero',
              }}
            />
          </g>
        </g>
      </g>
    </g>
  </SvgIcon>
);
export default SvgBullseyeThin;
