/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCeloLogo = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g clipPath="url(#celo_logo_svg__a)">
      <path
        fill="#FBCC5C"
        d="M9.474 21.474a6.947 6.947 0 1 0 0-13.895 6.947 6.947 0 0 0 0 13.895Zm0 2.526a9.474 9.474 0 1 1 0-18.948 9.474 9.474 0 0 1 0 18.948Z"
      />
      <path
        fill="#35D07F"
        d="M14.526 16.421a6.947 6.947 0 1 0 0-13.895 6.947 6.947 0 0 0 0 13.895Zm0 2.526a9.474 9.474 0 1 1 0-18.947 9.474 9.474 0 0 1 0 18.947Z"
      />
      <path
        fill="#5EA33B"
        d="M14.84 18.947a6.93 6.93 0 0 0 1.377-2.73 6.93 6.93 0 0 0 2.73-1.377 9.437 9.437 0 0 1-.736 3.37c-1.07.451-2.212.701-3.372.737ZM7.782 7.783a6.931 6.931 0 0 0-2.73 1.377 9.44 9.44 0 0 1 .736-3.371 9.439 9.439 0 0 1 3.372-.736 6.932 6.932 0 0 0-1.378 2.73Z"
      />
    </g>
    <defs>
      <clipPath id="celo_logo_svg__a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgCeloLogo;
