/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCertificateFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M13.347 2.557a1.912 1.912 0 0 0-2.698 0L8.84 4.37H6.277A1.908 1.908 0 0 0 4.37 6.277v2.564l-1.813 1.812a1.912 1.912 0 0 0 0 2.698L4.37 15.16v2.564c0 1.053.854 1.907 1.907 1.907h2.564l1.812 1.813a1.912 1.912 0 0 0 2.698 0l1.808-1.813h2.564a1.908 1.908 0 0 0 1.907-1.907v-2.564l1.813-1.812a1.912 1.912 0 0 0 0-2.698L19.63 8.84V6.277a1.908 1.908 0 0 0-1.907-1.907h-2.564l-1.812-1.813Z"
    />
  </SvgIcon>
);
export default SvgCertificateFill;
