/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCertificateLight = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <path
      d="M7.739 3.268a1.273 1.273 0 0 1-.898.373H4.277a.638.638 0 0 0-.636.636v2.564c0 .337-.135.659-.373.898L1.456 9.551a.637.637 0 0 0 0 .898l-.899.898a1.911 1.911 0 0 1 0-2.698L2.37 6.841V4.277c0-1.053.854-1.907 1.907-1.907h2.564L8.653.557a1.911 1.911 0 0 1 2.698 0l1.808 1.813h2.564c1.053 0 1.907.854 1.907 1.907v2.564l1.813 1.812a1.911 1.911 0 0 1 0 2.698l-1.813 1.808v2.564a1.907 1.907 0 0 1-1.907 1.907h-2.564l-1.812 1.813a1.911 1.911 0 0 1-2.698 0L6.841 17.63H4.277a1.907 1.907 0 0 1-1.907-1.907v-2.564L.557 11.347l.899-.898 1.812 1.812c.238.239.373.561.373.898v2.564c0 .35.286.636.636.636h2.564c.337 0 .659.135.898.373l1.812 1.812a.637.637 0 0 0 .898 0l1.812-1.812c.239-.238.561-.373.898-.373h2.564c.35 0 .636-.286.636-.636v-2.564c0-.337.135-.659.373-.898l1.812-1.812a.637.637 0 0 0 0-.898l-1.812-1.812a1.273 1.273 0 0 1-.373-.898V4.277a.638.638 0 0 0-.636-.636h-2.564c-.337 0-.659-.135-.898-.373l-1.812-1.812a.637.637 0 0 0-.898 0L7.739 3.268Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(1.17528 0 0 1.17527 .247 .247)"
    />
  </SvgIcon>
);
export default SvgCertificateLight;
