/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgCheck = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15.46 1.324a1.25 1.25 0 0 1 .185 1.758l-8.9 10.991a1.25 1.25 0 0 1-1.758.185L.59 10.698a1.25 1.25 0 0 1 1.573-1.943l3.425 2.773L13.702 1.51a1.25 1.25 0 0 1 1.758-.185Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgCheck;
