/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgClose = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M2.116 2.116a1.25 1.25 0 0 1 1.768 0l10 10a1.25 1.25 0 0 1-1.768 1.768l-10-10a1.25 1.25 0 0 1 0-1.768Z"
      fill="#000"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.884 2.116a1.25 1.25 0 0 1 0 1.768l-10 10a1.25 1.25 0 0 1-1.768-1.768l10-10a1.25 1.25 0 0 1 1.768 0Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgClose;
