/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCoOrg = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g fill="currentColor" clipPath="url(#co-org_svg__a)">
      <path d="M2.586 10.651a.973.973 0 0 0-.977.985v9.832a1.903 1.903 0 0 0 1.9 1.9h16.974a1.902 1.902 0 0 0 1.9-1.9v-9.832a.971.971 0 1 0-1.943 0v9.789H3.558v-9.789a.971.971 0 0 0-.972-.985ZM.973 9.68a.958.958 0 0 0 .537-.161l10.468-6.93 10.52 6.806a.971.971 0 1 0 1.056-1.632L13.003.933a1.879 1.879 0 0 0-2.056 0L.434 7.898A.972.972 0 0 0 .97 9.68h.002Z" />
      <path d="M6.6 14.551a1.551 1.551 0 1 0 0-3.102 1.551 1.551 0 0 0 0 3.102ZM12 14.554a1.553 1.553 0 1 0 .007-3.106A1.553 1.553 0 0 0 12 14.554ZM17.4 14.554a1.553 1.553 0 1 0 .007-3.106 1.553 1.553 0 0 0-.006 3.106ZM6.599 19.288a1.552 1.552 0 1 0-.006-3.103 1.552 1.552 0 0 0 .006 3.103ZM12 19.288a1.552 1.552 0 1 0 0-3.103 1.552 1.552 0 0 0 0 3.103ZM17.4 19.288a1.552 1.552 0 1 0 0-3.103 1.552 1.552 0 0 0 0 3.103Z" />
    </g>
    <defs>
      <clipPath id="co-org_svg__a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgCoOrg;
