/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgCopy = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.5 0A1.5 1.5 0 0 0 5 1.5V4H2.5A1.5 1.5 0 0 0 1 5.5v9A1.5 1.5 0 0 0 2.5 16h7a1.5 1.5 0 0 0 1.5-1.5V12h2.5a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 13.5 0h-7ZM9 12H6.5A1.5 1.5 0 0 1 5 10.5V6H3v8h6v-2Zm4-2H7V2h6v8Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgCopy;
