/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCreamFinanceColor = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g clipPath="url(#Cream_Finance_Color_svg__a)">
      <path
        d="m12.966 12.566 4.208 4.208a.801.801 0 0 1-.08 1.204 7.603 7.603 0 1 1 .03-11.936.793.793 0 0 1 .05 1.18l-4.21 4.212a.8.8 0 0 0-.234.579c-.002.11.02.219.064.32.039.097.098.185.172.259v-.026ZM12 0a12 12 0 1 0 0 24 12 12 0 0 0 0-24Z"
        fill="#69E2DC"
      />
    </g>
    <defs>
      <clipPath id="Cream_Finance_Color_svg__a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgCreamFinanceColor;
