/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgCylinder = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13396 0 0 .14926 -25.466 -25.002)"
    />
    <g transform="matrix(0 -1.31457 1.31457 0 .276 23.83)">
      <clipPath id="cylinder_svg__a">
        <path d="M0 0h18v22.5H0z" />
      </clipPath>
      <g clipPath="url(#cylinder_svg__a)">
        <path d="M18 3.5v11c0 2.08-4.039 3.5-9 3.5s-9-1.42-9-3.5v-11C0 1.43 4.039 0 9 0s9 1.43 9 3.5ZM1 5.17v9.33C1 15.74 4.573 17 9 17s8-1.26 8-2.5V5.17C15.499 6.3 12.457 7 9 7s-6.499-.7-8-1.83ZM9 6c4.427 0 8-1.26 8-2.5S13.427 1 9 1 1 2.26 1 3.5 4.573 6 9 6Z" />
      </g>
    </g>
  </SvgIcon>
);
export default SvgCylinder;
