/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgDocument = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M1.35.638c0-.352.286-.638.638-.638h11.78c.351 0 .637.286.637.638v14.724a.638.638 0 0 1-.638.638H1.988a.638.638 0 0 1-.638-.638V.638Zm1.276.638v13.448h10.503V1.276H2.626Zm1.669 2.798c0-.353.285-.638.638-.638h5.89a.638.638 0 0 1 0 1.276h-5.89a.638.638 0 0 1-.638-.638Zm0 3.926c0-.352.285-.638.638-.638h5.89a.638.638 0 0 1 0 1.276h-5.89A.638.638 0 0 1 4.295 8Zm0 3.926c0-.352.285-.638.638-.638h5.89a.638.638 0 0 1 0 1.276h-5.89a.638.638 0 0 1-.638-.638Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgDocument;
