/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgDownload = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="download_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#download_svg__a)">
        <path
          d="M288 32c0-17.7-14.3-32-32-32s-32 14.3-32 32v242.7l-73.4-73.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0l128-128c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L288 274.7V32ZM64 352c-35.3 0-64 28.7-64 64v32c0 35.3 28.7 64 64 64h384c35.3 0 64-28.7 64-64v-32c0-35.3-28.7-64-64-64H346.5l-45.3 45.3c-25 25-65.5 25-90.5 0L165.5 352H64Zm368 56c13.166 0 24 10.834 24 24s-10.834 24-24 24-24-10.834-24-24 10.834-24 24-24Z"
          style={{
            fillRule: 'nonzero',
          }}
          transform="matrix(.34995 0 0 .31404 190.107 167.501)"
        />
      </g>
    </g>
  </SvgIcon>
);
export default SvgDownload;
