/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgEas = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <path
      d="m321.718.045 4.338 21.685c.003.179.007 1.546.007 2.315h-10.7l.01-2.285L319.688.045h2.03Z"
      style={{
        fill: '#4d63b6',
      }}
      transform="matrix(1.70684 0 0 1 -535.375 -.045)"
    />
    <path
      d="m321.718.045 4.321 21.678c.014.835.009 1.54.024 2.322h-10.7l.01-2.285L319.688.045h2.03Z"
      style={{
        fill: '#7b93db',
      }}
      transform="matrix(1.0876 0 0 .63688 -336.788 5.144)"
    />
    <path
      d="m321.718.045 4.321 21.678c.014.835.009 1.54.024 2.322h-10.7l.01-2.285L319.688.045h2.03Z"
      style={{
        fill: '#bed0f7',
      }}
      transform="matrix(.50168 0 0 .29215 -148.866 10.278)"
    />
  </SvgIcon>
);
export default SvgEas;
