/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgEmail = (props: SvgIconProps) => (
  <SvgIcon
    width={17}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M.65 2a.65.65 0 0 0-.65.65v10.827c0 .36.291.65.65.65h14.724a.65.65 0 0 0 .65-.65V2.65a.65.65 0 0 0-.65-.65H.65Zm.65 2.064v8.763h13.424V4.064L8.435 9.459a.65.65 0 0 1-.846 0L1.3 4.064ZM13.618 3.3H2.406l5.606 4.81 5.606-4.81Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgEmail;
