/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgEthColorLogo = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m19.758 13.53-7.775 10.31v-5.788l7.775-4.522Z"
      fill="#C8B2F5"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m4.21 13.53 7.774 10.31v-5.788L4.209 13.53Z"
      fill="#EECBC0"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m4.207 12.335 7.776-3.458v7.882l-7.776-4.424Z"
      fill="#87A9F0"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="m19.759 12.335-7.776-3.458v7.882l7.776-4.424Z"
      fill="#CAB3F5"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.21 12.335 11.983.134v8.743l-7.775 3.458Z"
      fill="#EECBC0"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M19.758 12.335 11.983.134v8.743l7.775 3.458Z"
      fill="#B8FBF6"
      stroke="#3441C0"
      strokeWidth={0.011}
      strokeMiterlimit={7}
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </SvgIcon>
);
export default SvgEthColorLogo;
