/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgEthLogo = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g fill="none" fillRule="evenodd">
      <path d="M0 0h24v24H0z" />
      <path fill="#B2B2B2" fillRule="nonzero" d="M11.998 0v8.872l7.497 3.35z" />
      <path
        fill="#7F7F7F"
        fillRule="nonzero"
        d="M11.998 0 4.5 12.223l7.498-3.351z"
      />
      <path
        fill="#B2B2B2"
        fillRule="nonzero"
        d="M11.998 17.972V24L19.5 13.619z"
      />
      <path fill="#7F7F7F" fillRule="nonzero" d="M11.998 24v-6.03L4.5 13.62z" />
      <path
        fill="#E5E5E5"
        fillRule="nonzero"
        d="m11.998 16.577 7.497-4.354-7.497-3.349z"
      />
      <path
        fill="#B2B2B2"
        fillRule="nonzero"
        d="m4.5 12.223 7.498 4.354V8.874z"
      />
    </g>
  </SvgIcon>
);
export default SvgEthLogo;
