/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgEthLogo = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g opacity={0.5} fill="#000">
      <path d="M11.998 0v8.872l7.497 3.35L11.998 0Z" fillOpacity={0.602} />
      <path d="M11.998 0 4.5 12.223l7.498-3.351V0Z" />
      <path
        d="M11.998 17.972V24L19.5 13.619l-7.502 4.353Z"
        fillOpacity={0.602}
      />
      <path d="M11.998 24v-6.03L4.5 13.62 11.998 24Z" />
      <path
        d="m11.998 16.577 7.497-4.354-7.497-3.349v7.703Z"
        fillOpacity={0.2}
      />
      <path d="m4.5 12.223 7.498 4.354V8.874L4.5 12.223Z" fillOpacity={0.602} />
    </g>
  </SvgIcon>
);
export default SvgEthLogo;
