/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgFilter = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={16}
    height={16}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#B8BDBF"
      fillRule="evenodd"
      d="M.35 4A.65.65 0 0 1 1 3.35h14a.65.65 0 1 1 0 1.3H1A.65.65 0 0 1 .35 4Zm2.5 4a.65.65 0 0 1 .65-.65H13a.65.65 0 1 1 0 1.3H3.5A.65.65 0 0 1 2.85 8Zm2.5 4a.65.65 0 0 1 .65-.65h4.5a.65.65 0 1 1 0 1.3H6a.65.65 0 0 1-.65-.65Z"
      clipRule="evenodd"
    />
  </SvgIcon>
);
export default SvgFilter;
