/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgFlame = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.464 -25.002)"
    />
    <path
      d="M203.1 9.7 192 0l-11.1 9.7C104.2 76.8 45.7 162.2 10.9 258 3.7 277.8 0 299 0 320.2 0 425.4 86.8 512 192 512s192-86.6 192-191.8c0-21.1-3.7-42.3-10.9-62.2-34.8-95.8-93.3-181.2-170-248.3ZM208 144v15.9c0 12.9 5.2 25.2 14.3 34.2l47.1 46.4C291.5 262.2 304 292 304 323c0 60.2-48.8 109-109 109h-3c-61.9 0-112-50.6-112-112.4 0-25.5 12-49.6 32.4-64.9L128 243v55c0 24.3 19.8 44 44.1 44 24.2 0 43.9-19.6 43.9-43.8 0-11.6-4.6-22.8-12.8-31l-16.8-16.8c-11.7-11.7-18.3-27.7-18.3-44.3 0-19 8.6-37 23.5-48.9L208 144Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.04688 0 0 .04687 3 0)"
    />
  </SvgIcon>
);
export default SvgFlame;
