/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgGemSharpSolid = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M1 10.464 12 22l11-11.536L18.187 3H5.813L1 10.464Zm16.156-6.107-3.283 5.301 7.065.806L12 11.482l-8.938-1.018 7.065-.806-3.283-5.3L12 9.178l5.156-4.822Z"
    />
  </SvgIcon>
);
export default SvgGemSharpSolid;
