/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgGithub = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="M12 0C9.15 0 6.394 1.04 4.224 2.933a12.383 12.383 0 0 0-4.07 7.4 12.564 12.564 0 0 0 1.579 8.34 12.06 12.06 0 0 0 6.473 5.304c.6.108.824-.261.824-.585 0-.292-.014-1.261-.014-2.29-3.016.567-3.796-.755-4.036-1.447a4.47 4.47 0 0 0-1.23-1.738c-.42-.23-1.02-.8-.015-.815.384.043.752.18 1.073.4.321.219.586.515.772.861.164.303.385.569.65.784a2.504 2.504 0 0 0 2.845.232c.052-.626.324-1.211.765-1.647-2.67-.307-5.46-1.368-5.46-6.074A4.858 4.858 0 0 1 5.61 8.35a4.526 4.526 0 0 1 .12-3.26s1.005-.323 3.3 1.26a11.043 11.043 0 0 1 6 0c2.295-1.6 3.3-1.26 3.3-1.26a4.525 4.525 0 0 1 .12 3.26 4.83 4.83 0 0 1 1.23 3.307c0 4.72-2.805 5.767-5.475 6.074.286.298.507.655.646 1.048.14.393.196.812.164 1.229 0 1.646-.015 2.968-.015 3.383 0 .324.225.707.825.585a12.068 12.068 0 0 0 6.454-5.317 12.572 12.572 0 0 0 1.564-8.337 12.39 12.39 0 0 0-4.072-7.392A11.83 11.83 0 0 0 12 0Z"
      fill="#B8BDBF"
    />
  </SvgIcon>
);
export default SvgGithub;
