/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgGiveReceiveReceive = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.778 7.76a1 1 0 0 1-.109-1.41L12.826 5H6a1 1 0 1 1 0-2h6.826l-1.157-1.35a1 1 0 0 1 1.519-1.3l2.571 3a1 1 0 0 1 0 1.3l-2.571 3a1 1 0 0 1-1.41.11Z"
      fill="#E1E1E1"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.547 8.276A1 1 0 0 1 4.58 9.69L3.333 11H11a1 1 0 1 1 0 2H3.333l1.248 1.31a1 1 0 0 1-1.448 1.38l-2.857-3a1 1 0 0 1 0-1.38l2.857-3a1 1 0 0 1 1.414-.034Z"
      fill="#58B72B"
    />
  </SvgIcon>
);
export default SvgGiveReceiveReceive;
