/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgHome = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={25}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g clipPath="url(#home_svg__a)" fill="#000">
      <path d="M2.586 10.706a.971.971 0 0 0-.977.985v9.832a1.903 1.903 0 0 0 1.9 1.9h16.974a1.903 1.903 0 0 0 1.9-1.9V11.69a.971.971 0 1 0-1.943 0v9.789H3.558V11.69a.971.971 0 0 0-.972-.985ZM.973 9.735a.958.958 0 0 0 .537-.161l10.468-6.93 10.52 6.806a.971.971 0 1 0 1.056-1.632L13.003.988a1.879 1.879 0 0 0-2.056 0L.434 7.952A.972.972 0 0 0 .97 9.735h.002Z" />
      <path d="M6.6 14.606a1.551 1.551 0 1 0 0-3.103 1.551 1.551 0 0 0 0 3.103ZM12 14.609a1.554 1.554 0 1 0 .006-3.11A1.554 1.554 0 0 0 12 14.61ZM17.4 14.609a1.554 1.554 0 1 0 .006-3.11 1.554 1.554 0 0 0-.005 3.11ZM6.599 19.343a1.55 1.55 0 1 0-.005-3.102 1.55 1.55 0 0 0 .005 3.102ZM12 19.343a1.55 1.55 0 1 0 .001-3.102 1.55 1.55 0 0 0 0 3.102ZM17.4 19.343a1.55 1.55 0 1 0 .001-3.102 1.55 1.55 0 0 0 0 3.102Z" />
    </g>
    <defs>
      <clipPath id="home_svg__a">
        <path fill="#fff" transform="translate(0 .055)" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgHome;
