/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgHouseFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M22.994 11.98c0 .704-.573 1.254-1.222 1.254H20.55l.026 6.258c0 .106-.007.211-.019.317v.628c0 .864-.684 1.563-1.528 1.563h-.61c-.043 0-.085 0-.127-.004-.053.004-.107.004-.16.004h-2.159c-.844 0-1.527-.7-1.527-1.563V17c0-.691-.547-1.25-1.223-1.25H10.78c-.676 0-1.223.559-1.223 1.25V20.438C9.556 21.3 8.873 22 8.028 22H5.893a2.53 2.53 0 0 1-.172-.008 1.622 1.622 0 0 1-.137.008h-.611c-.845 0-1.528-.7-1.528-1.563v-4.375c0-.035 0-.074.003-.109v-2.719H2.222C1.535 13.234 1 12.688 1 11.98c0-.351.115-.664.382-.937l9.794-8.73c.267-.274.573-.313.84-.313.268 0 .573.078.802.273l9.756 8.77c.306.273.458.586.42.937Z"
    />
  </SvgIcon>
);
export default SvgHouseFill;
