/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgLightSolid = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M6.286 15.45c0 .303.257.55.571.55h2.286a.563.563 0 0 0 .571-.55V13.9H6.286v1.55ZM8 4C5.794 4 4 5.727 4 7.85c0 1.309.68 2.459 1.714 3.157v1.243c0 .303.257.55.572.55h3.428a.563.563 0 0 0 .572-.55v-1.243C11.32 10.309 12 9.159 12 7.85 12 5.727 10.206 4 8 4ZM3 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM15 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM16 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM4 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM14 3a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM9 1a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgLightSolid;
