/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgLinks = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#1E3050"
      fillRule="nonzero"
      d="M8.838 17.618A7.724 7.724 0 0 1 7.4 13.125c0-3.484 2.31-6.437 5.516-7.478A6.96 6.96 0 0 0 8.55 4.125c-3.81 0-6.9 3.023-6.9 6.75s3.09 6.75 6.9 6.75c.097 0 .194-.004.287-.007Zm1.308-.176c3.04-.703 5.304-3.378 5.304-6.567a6.64 6.64 0 0 0-1.596-4.317c-3.04.703-5.304 3.378-5.304 6.567 0 1.642.6 3.146 1.596 4.317Zm-.417 1.224c-.385.056-.78.084-1.179.084-4.445 0-8.05-3.526-8.05-7.875S4.105 3 8.55 3c2.239 0 4.262.893 5.721 2.334a8.122 8.122 0 0 1 1.179-.084c4.445 0 8.05 3.526 8.05 7.875S19.895 21 15.45 21a8.114 8.114 0 0 1-5.721-2.334Zm5.434-12.284a7.732 7.732 0 0 1 1.437 4.493c0 3.484-2.31 6.437-5.516 7.478a6.96 6.96 0 0 0 4.366 1.522c3.81 0 6.9-3.023 6.9-6.75s-3.09-6.75-6.9-6.75c-.097 0-.194.004-.287.007Z"
    />
  </SvgIcon>
);
export default SvgLinks;
