/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgLinks = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.464 -25.002)"
    />
    <path
      d="M8.838 14.618A7.722 7.722 0 0 1 7.4 10.125c0-3.484 2.311-6.437 5.516-7.478A6.962 6.962 0 0 0 8.55 1.125c-3.809 0-6.9 3.023-6.9 6.75s3.091 6.75 6.9 6.75c.097 0 .194-.004.288-.007Zm1.308-.176c3.04-.703 5.304-3.378 5.304-6.567 0-1.642-.6-3.146-1.596-4.317-3.04.703-5.304 3.378-5.304 6.567 0 1.642.6 3.146 1.596 4.317Zm-.417 1.224c-.385.056-.78.084-1.179.084C4.105 15.75.5 12.224.5 7.875S4.105 0 8.55 0c2.239 0 4.262.893 5.721 2.334a8.17 8.17 0 0 1 1.179-.084c4.445 0 8.05 3.526 8.05 7.875S19.895 18 15.45 18a8.115 8.115 0 0 1-5.721-2.334Zm5.434-12.284A7.736 7.736 0 0 1 16.6 7.875c0 3.484-2.311 6.437-5.516 7.478a6.962 6.962 0 0 0 4.366 1.522c3.809 0 6.9-3.023 6.9-6.75s-3.091-6.75-6.9-6.75c-.097 0-.194.004-.287.007Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(1.04147 .32598 -.32598 1.04147 2.434 -1.029)"
    />
  </SvgIcon>
);
export default SvgLinks;
