/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMedium = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="M13.292 11.992c0 3.413-2.75 6.18-6.142 6.18-3.392 0-6.141-2.767-6.141-6.18s2.75-6.18 6.141-6.18c3.392 0 6.142 2.767 6.142 6.18ZM20.026 12.005c0 3.212-1.374 5.818-3.07 5.818-1.696 0-3.071-2.606-3.071-5.818 0-3.212 1.374-5.818 3.07-5.818 1.696 0 3.071 2.605 3.071 5.818M22.8 12.008c0 2.878-.484 5.212-1.08 5.212-.597 0-1.08-2.333-1.08-5.211 0-2.879.483-5.212 1.08-5.212.596 0 1.08 2.333 1.08 5.212Z"
      fill="currentColor"
    />
  </SvgIcon>
);
export default SvgMedium;
