/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMessagesQuestion = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M1 5.25C1 4.01 1.987 3 3.2 3h9.9c1.213 0 2.2 1.009 2.2 2.25V12c0 1.241-.987 2.25-2.2 2.25H7.968L5.18 16.388a.545.545 0 0 1-.577.053.555.555 0 0 1-.303-.503V14.25H3.2C1.987 14.25 1 13.241 1 12V5.25Zm8.8 10.126h3.3c1.822 0 3.3-1.512 3.3-3.376V7.5h4.4c1.213 0 2.2 1.01 2.2 2.25v6.75c0 1.242-.987 2.25-2.2 2.25h-1.1v1.688a.561.561 0 0 1-.302.503.546.546 0 0 1-.578-.053l-2.788-2.137H12c-1.213 0-2.2-1.01-2.2-2.25v-1.125ZM5.682 6.249l-.014.035a.707.707 0 0 0 .42.896c.357.13.749-.063.876-.429l.014-.035a.227.227 0 0 1 .216-.155h1.668c.24 0 .433.2.433.443a.442.442 0 0 1-.217.384l-1.272.749a.707.707 0 0 0-.343.608v.394c0 .386.309.703.687.703.375 0 .68-.31.688-.69l.924-.54c.56-.331.908-.943.908-1.604 0-1.023-.812-1.85-1.808-1.85H7.194c-.68 0-1.285.437-1.512 1.094V6.25Zm3.386 5.47a.945.945 0 0 0-.441-.86.9.9 0 0 0-.95 0 .945.945 0 0 0-.441.86c-.021.349.149.68.44.86a.9.9 0 0 0 .95 0 .945.945 0 0 0 .442-.86Z"
    />
  </SvgIcon>
);
export default SvgMessagesQuestion;
