/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMessageSolid = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M3.75 1A2.753 2.753 0 0 0 1 3.75v12.376a2.753 2.753 0 0 0 2.75 2.75h4.125v3.437c0 .263.146.499.378.615.232.116.511.09.722-.065l5.315-3.987h5.96a2.753 2.753 0 0 0 2.75-2.75V3.75A2.753 2.753 0 0 0 20.25 1H3.75Z"
    />
  </SvgIcon>
);
export default SvgMessageSolid;
