/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMessageHeart = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="message-heart_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#message-heart_svg__a)">
        <path
          d="M0 64C0 28.7 28.7 0 64 0h384c35.3 0 64 28.7 64 64v288c0 35.3-28.7 64-64 64H309.3l-123.7 92.8c-4.8 3.6-11.3 4.2-16.8 1.5s-8.8-8.2-8.8-14.3v-80H64c-35.3 0-64-28.7-64-64V64Zm205.3 48c-33.8 0-61.3 27.4-61.3 61.3 0 16.2 6.5 31.8 17.9 43.3l82.7 82.7c6.2 6.2 16.4 6.2 22.6 0l82.7-82.7c11.5-11.5 17.9-27.1 17.9-43.3 0-33.8-27.4-61.3-61.3-61.3-16.2 0-31.8 6.5-43.3 17.9l-7.4 7.4-7.4-7.4c-11.5-11.5-27.1-17.9-43.3-17.9h.2Z"
          style={{
            fillRule: 'nonzero',
          }}
          transform="matrix(.34995 0 0 .31406 190.107 167.501)"
        />
      </g>
    </g>
  </SvgIcon>
);
export default SvgMessageHeart;
