/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMessage = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M7.875 16.813c1.139 0 2.063.924 2.063 2.063v.687l3.115-2.337a2.07 2.07 0 0 1 1.237-.413h5.96a.69.69 0 0 0 .688-.687V3.75a.69.69 0 0 0-.688-.687H3.75a.69.69 0 0 0-.688.687v12.376c0 .378.31.687.688.687h4.125Zm2.063 5.329-.01.008-.218.163-.735.55a.694.694 0 0 1-.722.065.677.677 0 0 1-.378-.615V18.876H3.75A2.753 2.753 0 0 1 1 16.126V3.75A2.753 2.753 0 0 1 3.75 1h16.5A2.753 2.753 0 0 1 23 3.75v12.376a2.753 2.753 0 0 1-2.75 2.75h-5.96l-4.352 3.266Z"
    />
  </SvgIcon>
);
export default SvgMessage;
