/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMetaMaskColor = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#CDBDB2"
      fillRule="evenodd"
      d="m6.866 20.7 3.145.835v-1.091l.256-.257h1.797v2.182H10.14l-2.374-1.027-.899-.641Z"
      clipRule="evenodd"
    />
    <path
      fill="#CDBDB2"
      fillRule="evenodd"
      d="m17.134 20.7-3.08.835v-1.091l-.257-.257H12v2.182h1.925l2.374-1.027.835-.641Z"
      clipRule="evenodd"
    />
    <path
      fill="#393939"
      fillRule="evenodd"
      d="m10.267 18.327-.257 2.117.32-.256h3.338l.385.256-.257-2.117-.513-.321-2.567.064-.45.256Z"
      clipRule="evenodd"
    />
    <path
      fill="#F89C35"
      fillRule="evenodd"
      d="m8.534 4.016 1.54 3.594.706 10.46h2.503l.77-10.46 1.412-3.594h-6.93Z"
      clipRule="evenodd"
    />
    <path
      fill="#F89D35"
      fillRule="evenodd"
      d="M1.797 11.91 0 17.106l4.492-.257H7.38v-2.246l-.129-4.62-.641.514-4.813 1.411Z"
      clipRule="evenodd"
    />
    <path
      fill="#D87C30"
      fillRule="evenodd"
      d="m5.197 12.487 5.262.128-.577 2.696-2.503-.642-2.182-2.182Z"
      clipRule="evenodd"
    />
    <path
      fill="#EA8D3A"
      fillRule="evenodd"
      d="m5.197 12.551 2.182 2.053v2.054l-2.182-4.107Z"
      clipRule="evenodd"
    />
    <path
      fill="#F89D35"
      fillRule="evenodd"
      d="m7.38 14.67 2.568.64.834 2.76-.578.321-2.823-1.668v-2.054Z"
      clipRule="evenodd"
    />
    <path
      fill="#EB8F35"
      fillRule="evenodd"
      d="m7.38 16.722-.514 3.98 3.401-2.375-2.887-1.605Z"
      clipRule="evenodd"
    />
    <path
      fill="#EA8E3A"
      fillRule="evenodd"
      d="m10.46 12.615.321 5.455-.963-2.792.642-2.663Z"
      clipRule="evenodd"
    />
    <path
      fill="#D87C30"
      fillRule="evenodd"
      d="m4.429 16.787 2.952-.065-.514 3.98-2.438-3.915Z"
      clipRule="evenodd"
    />
    <path
      fill="#EB8F35"
      fillRule="evenodd"
      d="M1.412 22.434 6.866 20.7l-2.438-3.915L0 17.107l1.412 5.326Z"
      clipRule="evenodd"
    />
    <path
      fill="#E8821E"
      fillRule="evenodd"
      d="M10.074 7.61 7.315 9.92l-2.118 2.567 5.262.192-.385-5.07Z"
      clipRule="evenodd"
    />
    <path
      fill="#DFCEC3"
      fillRule="evenodd"
      d="m6.866 20.701 3.401-2.374-.256 2.053v1.156l-2.31-.45-.835-.385ZM17.134 20.701l-3.337-2.374.256 2.053v1.156l2.31-.45.77-.385Z"
      clipRule="evenodd"
    />
    <path
      fill="#393939"
      fillRule="evenodd"
      d="m9.049 13.77.706 1.476-2.503-.641 1.797-.835Z"
      clipRule="evenodd"
    />
    <path
      fill="#E88F35"
      fillRule="evenodd"
      d="m1.347 1 8.727 6.61-1.476-3.594L1.347 1Z"
      clipRule="evenodd"
    />
    <path
      fill="#8E5A30"
      fillRule="evenodd"
      d="M1.347 1 .192 4.53l.642 3.85-.45.257.643.577-.514.45.706.641-.45.385 1.028 1.284 4.813-1.476c2.353-1.883 3.508-2.845 3.465-2.888-.043-.043-2.952-2.246-8.728-6.61Z"
      clipRule="evenodd"
    />
    <path
      fill="#F89D35"
      fillRule="evenodd"
      d="M22.202 11.91 24 17.106l-4.492-.257h-2.888v-2.246l.129-4.62.641.514 4.813 1.411Z"
      clipRule="evenodd"
    />
    <path
      fill="#D87C30"
      fillRule="evenodd"
      d="m18.803 12.487-5.262.128.577 2.696 2.503-.642 2.182-2.182Z"
      clipRule="evenodd"
    />
    <path
      fill="#EA8D3A"
      fillRule="evenodd"
      d="m18.803 12.552-2.182 2.053v2.053l2.182-4.107Z"
      clipRule="evenodd"
    />
    <path
      fill="#F89D35"
      fillRule="evenodd"
      d="m16.62 14.67-2.567.64-.834 2.76.578.321 2.823-1.668v-2.054Z"
      clipRule="evenodd"
    />
    <path
      fill="#EB8F35"
      fillRule="evenodd"
      d="m16.62 16.722.514 3.98-3.337-2.311 2.823-1.669Z"
      clipRule="evenodd"
    />
    <path
      fill="#EA8E3A"
      fillRule="evenodd"
      d="m13.54 12.615-.321 5.455.963-2.792-.642-2.663Z"
      clipRule="evenodd"
    />
    <path
      fill="#D87C30"
      fillRule="evenodd"
      d="m19.573 16.787-2.952-.065.514 3.98 2.438-3.915Z"
      clipRule="evenodd"
    />
    <path
      fill="#EB8F35"
      fillRule="evenodd"
      d="m22.587 22.434-5.454-1.733 2.438-3.914 4.428.32-1.412 5.327Z"
      clipRule="evenodd"
    />
    <path
      fill="#E8821E"
      fillRule="evenodd"
      d="m13.926 7.61 2.759 2.31 2.118 2.567-5.262.192.385-5.07Z"
      clipRule="evenodd"
    />
    <path
      fill="#393939"
      fillRule="evenodd"
      d="m14.952 13.77-.706 1.476 2.503-.641-1.797-.835Z"
      clipRule="evenodd"
    />
    <path
      fill="#E88F35"
      fillRule="evenodd"
      d="m22.652 1-8.727 6.61 1.476-3.594L22.652 1Z"
      clipRule="evenodd"
    />
    <path
      fill="#8E5A30"
      fillRule="evenodd"
      d="m22.653 1 1.155 3.53-.642 3.85.45.257-.643.577.514.45-.706.641.45.385-1.028 1.284-4.813-1.476c-2.353-1.883-3.508-2.845-3.465-2.888.043-.043 2.952-2.246 8.728-6.61Z"
      clipRule="evenodd"
    />
  </SvgIcon>
);
export default SvgMetaMaskColor;
