/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgMeteor = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.001)"
    />
    <path
      d="M474.8 0c-5.2 0-10.3 1.1-15 3.2L324 62.9l1.4-18.2c2.5-34.2-36.2-55.5-63.7-35.1l-179 132.9C30.6 181.2 0 242.7 0 307.5 0 419.8 91 512 203.6 512c65.7 0 127.4-31.8 165.7-85.3l126.3-176.9c19.7-27.6-1.8-65.7-35.6-63.1l-10.7.8 59.5-135.3c2.1-4.7 3.2-9.8 3.2-15C512 16.7 495.3 0 474.8 0Zm-168 122.9 147-64.7-64.6 146.7c-3.4 7.7-2.5 16.7 2.4 23.5 4.9 6.8 13 10.7 21.4 10.1l33.5-2.6-116.4 163C301 439.7 253.8 464 203.6 464 117.8 464 48 393.6 48 307.5c0-49.7 23.6-96.9 63.4-126.5L276.2 58.6l-3 40.6c-.6 8.4 3.2 16.5 10.1 21.4 6.9 4.9 15.8 5.8 23.5 2.4v-.1ZM200 424c61.441 0 112-50.559 112-112s-50.559-112-112-112S88 250.559 88 312s50.559 112 112 112Zm-24-160c13.166 0 24 10.834 24 24s-10.834 24-24 24-24-10.834-24-24 10.834-24 24-24Zm24 96c0-8.777 7.223-16 16-16 8.777 0 16 7.223 16 16 0 8.777-7.223 16-16 16-8.777 0-16-7.223-16-16Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.04633 0 0 .04633 .058 .281)"
    />
  </SvgIcon>
);
export default SvgMeteor;
