/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgMore = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M4 8a2 2 0 1 0-4 0 2 2 0 0 0 4 0ZM10 8a2 2 0 1 0-4 0 2 2 0 0 0 4 0ZM16 8a2 2 0 1 0-4 0 2 2 0 0 0 4 0Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgMore;
