/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgOptimismLogo = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <circle
      cx={11}
      cy={11}
      r={11}
      style={{
        fill: '#ff0420',
      }}
      transform="rotate(180 12 12) scale(1.09091)"
    />
    <path
      d="M7.447 14c-.719 0-1.308-.156-1.767-.467-.453-.316-.68-.766-.68-1.35 0-.122.015-.272.045-.45.079-.4.191-.88.336-1.441C5.792 8.764 6.852 8 8.562 8c.465 0 .882.072 1.251.217.368.139.658.35.87.633.211.278.317.611.317 1 0 .117-.015.264-.045.442-.091.494-.2.975-.327 1.441-.211.761-.577 1.331-1.096 1.709-.52.372-1.215.558-2.085.558Zm.127-1.2c.338 0 .625-.092.861-.275.242-.183.414-.464.517-.842.139-.522.244-.978.317-1.366.024-.117.036-.236.036-.359 0-.505-.287-.758-.861-.758-.338 0-.628.092-.87.275-.236.183-.405.464-.508.842a17.27 17.27 0 0 0-.326 1.366 1.655 1.655 0 0 0-.036.35c0 .511.29.767.87.767ZM11.181 14a.191.191 0 0 1-.15-.06.2.2 0 0 1-.026-.154l1.217-5.572a.24.24 0 0 1 .097-.154.272.272 0 0 1 .167-.06h2.345c.653 0 1.176.131 1.569.394.4.263.6.643.6 1.14 0 .143-.018.292-.053.446-.147.657-.444 1.143-.89 1.457-.441.314-1.047.472-1.816.472H13.05l-.405 1.877a.244.244 0 0 1-.097.154.274.274 0 0 1-.168.06h-1.199Zm3.121-3.274c.247 0 .462-.066.644-.197a.926.926 0 0 0 .37-.566c.018-.097.027-.183.027-.257 0-.166-.05-.292-.15-.377-.1-.092-.271-.138-.512-.138h-1.058l-.335 1.535h1.014Z"
      style={{
        fill: '#fff',
        fillRule: 'nonzero',
      }}
      transform="scale(1.09091)"
    />
  </SvgIcon>
);
export default SvgOptimismLogo;
