/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgParcel = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path fill="currentColor" d="M19.246 4.9v6.11l-7.052 4.293V0l7.052 4.9Z" />
    <path fill="currentColor" d="M12.195 15.303V24l-7.052-4.406 7.052-4.292Z" />
    <path
      fill="currentColor"
      d="M12.195 0v15.303l-7.052 4.29V4.899L12.195 0Z"
    />
  </SvgIcon>
);
export default SvgParcel;
