/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgPlanetFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M19.821 3.217a.062.062 0 1 0-.122.025.062.062 0 0 0 .122-.025ZM18.2 5.277c.418-.25.796-.449 1.128-.605-.16.332-.359.71-.605 1.129-.172.289-.36.59-.562.902a8.113 8.113 0 0 0-.86-.86c.313-.203.613-.394.902-.562l-.003-.004ZM4.566 15.29c-2.16 3.05-3.113 5.527-2.25 6.394 1.375 1.375 6.824-1.848 12.172-7.195 5.347-5.348 8.57-10.797 7.195-12.172-.867-.863-3.344.09-6.394 2.25a8.105 8.105 0 0 0-3.29-.691A8.123 8.123 0 0 0 3.876 12c0 1.171.246 2.28.691 3.289ZM5.84 17.3c.265.309.55.594.859.86-.312.203-.613.394-.902.562-.418.25-.797.45-1.13.605.161-.332.36-.71.606-1.128.172-.29.36-.59.563-.903l.004.004Zm-2.623 2.521a.062.062 0 1 0 .025-.122.062.062 0 0 0-.025.122Zm.97.917a.07.07 0 1 0 .118.074.07.07 0 1 0-.118-.074Zm16.55-16.55a.07.07 0 1 0 .075.117.07.07 0 1 0-.074-.118ZM12 20.123a8.123 8.123 0 0 0 7.917-9.956c-1.242 1.664-2.789 3.445-4.546 5.203-1.758 1.757-3.54 3.304-5.203 4.546.59.137 1.199.207 1.832.207Z"
    />
  </SvgIcon>
);
export default SvgPlanetFill;
