/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgPlus = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9 1a1 1 0 1 0-2 0v6H1a1 1 0 0 0 0 2h6v6a1 1 0 1 0 2 0V9h6a1 1 0 1 0 0-2H9V1Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgPlus;
