/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgPolygonMaticLogo = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    fill="none"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <g clipPath="url(#polygon-matic-logo_svg__a)">
      <path
        fill="#8247E5"
        d="M18.125 7.307c-.437-.286-1-.286-1.5 0l-3.5 2.365-2.375 1.504-3.437 2.364c-.438.287-1 .287-1.5 0l-2.688-1.862c-.437-.287-.75-.86-.75-1.505V6.591c0-.573.25-1.146.75-1.504l2.688-1.791c.437-.287 1-.287 1.5 0L10 5.158c.438.287.75.86.75 1.505v2.364l2.375-1.576V5.015c0-.573-.25-1.146-.75-1.505l-5-3.367c-.437-.286-1-.286-1.5 0L.75 3.583c-.5.286-.75.859-.75 1.432v6.734c0 .573.25 1.146.75 1.505l5.063 3.367c.437.286 1 .286 1.5 0l3.437-2.293 2.375-1.576 3.438-2.292c.437-.287 1-.287 1.5 0l2.687 1.79c.438.287.75.86.75 1.505v3.582c0 .573-.25 1.147-.75 1.505l-2.625 1.79c-.437.287-1 .287-1.5 0l-2.687-1.79c-.438-.287-.75-.86-.75-1.505v-2.292l-2.376 1.576v2.364c0 .573.25 1.146.75 1.505l5.063 3.367c.438.286 1 .286 1.5 0l5.063-3.367c.437-.287.75-.86.75-1.505V12.18c0-.573-.25-1.146-.75-1.504l-5.063-3.368Z"
      />
    </g>
    <defs>
      <clipPath id="polygon-matic-logo_svg__a">
        <path fill="#fff" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </SvgIcon>
);
export default SvgPolygonMaticLogo;
