/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgScale = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="M22.96 11.294c-.005-.02 0-.042-.007-.063L20.39 4.4h1.875a.733.733 0 0 0 0-1.467h-9.533v-2.2a.734.734 0 0 0-1.466 0v2.2H1.732a.734.734 0 0 0 0 1.467H3.61l-2.562 6.832c-.008.02-.002.042-.008.062A.708.708 0 0 0 1 11.49c0 .025.007.048.007.073l.004.03a3.658 3.658 0 0 0 7.312 0l.003-.03c0-.025.007-.048.007-.073a.702.702 0 0 0-.04-.195c-.005-.02.001-.042-.007-.062L5.725 4.4h5.542v16.133H5.644a.733.733 0 0 0 0 1.467h12.712a.733.733 0 0 0 0-1.467h-5.623V4.4h5.542l-2.561 6.832c-.008.02-.002.042-.008.062a.702.702 0 0 0-.04.195c0 .025.008.048.008.073l.003.031a3.658 3.658 0 0 0 7.313 0l.003-.03c0-.026.007-.049.007-.074a.71.71 0 0 0-.04-.195ZM4.667 13.69a2.203 2.203 0 0 1-2.074-1.467H6.74a2.204 2.204 0 0 1-2.074 1.467ZM2.79 10.755l1.876-5 1.875 5h-3.75Zm16.542-5 1.876 5h-3.751l1.875-5Zm0 7.934a2.203 2.203 0 0 1-2.074-1.467h4.148a2.202 2.202 0 0 1-2.074 1.467Z"
      fill="currentColor"
    />
  </SvgIcon>
);
export default SvgScale;
