/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgSearchFa = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="search-fa_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#search-fa_svg__a)">
        <g transform="matrix(.34995 0 0 .31404 190.107 167.501)">
          <clipPath id="search-fa_svg__b">
            <path d="M0 0h512v512H0z" />
          </clipPath>
          <g clipPath="url(#search-fa_svg__b)">
            <path
              d="M368 208c0-87.773-72.227-160-160-160S48 120.227 48 208s72.227 160 160 160 160-72.227 160-160Zm-30.9 163.1C301.7 399.2 256.8 416 208 416 93.1 416 0 322.9 0 208S93.1 0 208 0s208 93.1 208 208c0 48.8-16.8 93.7-44.9 129.1L505 471c9.4 9.4 9.4 24.6 0 33.9-9.4 9.3-24.6 9.4-33.9 0l-134-133.8Z"
              style={{
                fillRule: 'nonzero',
              }}
            />
          </g>
        </g>
      </g>
    </g>
  </SvgIcon>
);
export default SvgSearchFa;
