/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgSearch = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.083 11.164a6.822 6.822 0 1 0-.919.919l.016.016 3.709 3.709a.65.65 0 0 0 .92-.92l-3.71-3.709a.58.58 0 0 0-.016-.015Zm.26-4.342a5.522 5.522 0 1 1-11.043 0 5.522 5.522 0 0 1 11.043 0Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgSearch;
