/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgShareSolid = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M14.191 2.12a1.358 1.358 0 0 0-.816 1.238v2.714H8.562C4.386 6.072 1 9.414 1 13.536c0 4.805 3.502 6.95 4.305 7.383.108.06.228.081.349.081a.843.843 0 0 0 .846-.835c0-.319-.185-.611-.421-.827-.404-.378-.954-1.12-.954-2.41 0-2.247 1.848-4.07 4.125-4.07h4.125v2.714c0 .534.318 1.022.816 1.238a1.394 1.394 0 0 0 1.479-.229l6.875-6.107c.287-.259.455-.623.455-1.01 0-.385-.163-.75-.455-1.009L15.67 2.35a1.379 1.379 0 0 0-1.479-.23Z"
    />
  </SvgIcon>
);
export default SvgShareSolid;
