/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgShareGive = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <g transform="matrix(.04688 0 0 .04687 1.5 0)">
      <clipPath id="share-give_svg__a">
        <path d="M0 0h448v512H0z" />
      </clipPath>
      <g clipPath="url(#share-give_svg__a)">
        <path
          d="M448 112c0 44.2-35.8 80-80 80-22.9 0-43.6-9.6-58.1-25l-151 75.5c.8 4.4 1.1 8.9 1.1 13.5s-.4 9.1-1.1 13.5l151 75.5c14.6-15.4 35.2-25 58.1-25 44.2 0 80 35.8 80 80s-35.8 80-80 80-80-35.8-80-80c0-9.7 1.7-19 4.9-27.7l-145.7-72.8c-14.3 22-39 36.5-67.2 36.5-44.2 0-80-35.8-80-80s35.8-80 80-80c28.2 0 52.9 14.5 67.2 36.5l145.7-72.9c-3.2-8.6-4.9-17.9-4.9-27.7 0-44.2 35.8-80 80-80s80 35.8 80 80v.1ZM80 304c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Zm336-192c0-26.332-21.668-48-48-48s-48 21.668-48 48 21.668 48 48 48 48-21.668 48-48Zm-48 336c26.332 0 48-21.668 48-48s-21.668-48-48-48-48 21.668-48 48 21.668 48 48 48Z"
          style={{
            fillRule: 'nonzero',
          }}
        />
      </g>
    </g>
  </SvgIcon>
);
export default SvgShareGive;
