/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgStars = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <g transform="matrix(.13395 0 0 .14926 -25.465 -25.002)">
      <path
        d="M190.107 167.501h179.172v160.79H190.107z"
        style={{
          fill: 'none',
        }}
      />
      <clipPath id="stars_svg__a">
        <path d="M190.107 167.501h179.172v160.79H190.107z" />
      </clipPath>
      <g clipPath="url(#stars_svg__a)">
        <g transform="matrix(.3479 0 0 .3122 192.203 168.442)">
          <clipPath id="stars_svg__b">
            <path d="M0 0h512v512H0z" />
          </clipPath>
          <g clipPath="url(#stars_svg__b)">
            <path
              d="M325.8 152.3c1.3 4.6 5.5 7.7 10.2 7.7 4.7 0 8.9-3.1 10.2-7.7L360 104l48.3-13.8c4.6-1.3 7.7-5.5 7.7-10.2 0-4.7-3.1-8.9-7.7-10.2L360 56 346.2 7.7C344.9 3.1 340.7 0 336 0c-4.7 0-8.9 3.1-10.2 7.7L312 56l-48.3 13.8c-4.6 1.3-7.7 5.5-7.7 10.2 0 4.7 3.1 8.9 7.7 10.2L312 104l13.8 48.3ZM115.7 346.2 75.5 307l55.5-8.1c15.6-2.3 29.2-12.1 36.1-26.3l24.8-50.3 24.8 50.3c7 14.2 20.5 24 36.1 26.3l55.5 8.1-40.2 39.2c-11.3 11-16.4 26.9-13.8 42.4l9.5 55.4-49.5-26.1c-14-7.4-30.7-7.4-44.7 0L120 444l9.5-55.4c2.7-15.6-2.5-31.4-13.8-42.4Zm54.7-188.8-46.3 94-103.6 15.1C.9 269.3-7 293.5 7.2 307.4l74.9 73.2-17.6 103.3c-3.4 19.6 17.2 34.6 34.8 25.3l92.6-48.8 92.6 48.8c17.6 9.3 38.2-5.7 34.8-25.3l-17.7-103.3 74.9-73.2c14.2-13.9 6.4-38.1-13.3-40.9l-103.5-15.1-46.3-94c-8.8-17.9-34.3-17.9-43.1 0h.1Zm258.4 85.8 11 38.6c1 3.6 4.4 6.2 8.2 6.2 3.8 0 7.1-2.5 8.2-6.2l11-38.6 38.6-11c3.6-1 6.2-4.4 6.2-8.2 0-3.8-2.5-7.1-6.2-8.2l-38.6-11-11-38.6c-1-3.6-4.4-6.2-8.2-6.2-3.8 0-7.1 2.5-8.2 6.2l-11 38.6-38.6 11c-3.6 1-6.2 4.4-6.2 8.2 0 3.8 2.5 7.1 6.2 8.2l38.6 11Z"
              style={{
                fillRule: 'nonzero',
              }}
            />
          </g>
        </g>
      </g>
    </g>
  </SvgIcon>
);
export default SvgStars;
