/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgTelegram = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0Zm2.544 12.122a.565.565 0 0 1-.802.281L7.57 10.715l-1.393 1.287a.24.24 0 0 1-.228.03l.267-2.39.008.007.006-.047s3.908-3.559 4.067-3.71c.161-.151.108-.184.108-.184.01-.184-.289 0-.289 0L4.938 9.039l-2.156-.734s-.332-.119-.363-.38c-.033-.26.373-.4.373-.4l8.574-3.407s.704-.313.704.207l-1.526 7.797Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgTelegram;
