/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgTimelineList = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <path
      d="M16 96c0-26.332 21.668-48 48-48s48 21.668 48 48-21.668 48-48 48-48-21.668-48-48Zm48 112c26.332 0 48 21.668 48 48s-21.668 48-48 48-48-21.668-48-48 21.668-48 48-48Zm0 160c26.332 0 48 21.668 48 48s-21.668 48-48 48-48-21.668-48-48 21.668-48 48-48ZM191.5 54.4c5.5-4.2 12.3-6.4 19.2-6.4H424c13.3 0 24 10.7 24 24v48c0 13.3-10.7 24-24 24H210.7c-6.9 0-13.7-2.2-19.2-6.4l-38.4-28.8c-8.5-6.4-8.5-19.2 0-25.6l38.4-28.8Zm-38.4 188.8 38.4-28.8c5.5-4.2 12.3-6.4 19.2-6.4H488c13.3 0 24 10.7 24 24v48c0 13.3-10.7 24-24 24H210.7c-6.9 0-13.7-2.2-19.2-6.4l-38.4-28.8c-8.5-6.4-8.5-19.2 0-25.6Zm0 160 38.4-28.8c5.5-4.2 12.3-6.4 19.2-6.4H424c13.3 0 24 10.7 24 24v48c0 13.3-10.7 24-24 24H210.7c-6.9 0-13.7-2.2-19.2-6.4l-38.4-28.8c-8.5-6.4-8.5-19.2 0-25.6Z"
      style={{
        fillRule: 'nonzero',
      }}
      transform="matrix(.04518 0 0 .04518 0 .435)"
    />
  </SvgIcon>
);
export default SvgTimelineList;
