/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgTime = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M8 16c-4.4 0-8-3.6-8-8s3.6-8 8-8 8 3.6 8 8-3.6 8-8 8ZM8 1.333c-3.667 0-6.667 3-6.667 6.667s3 6.667 6.667 6.667 6.667-3 6.667-6.667-3-6.667-6.667-6.667Z"
      fill="#000"
    />
    <path
      d="M8 8.667c-.4 0-.667-.267-.667-.667V3.333c0-.4.267-.666.667-.666s.667.266.667.666V8c0 .4-.267.667-.667.667Z"
      fill="#000"
    />
    <path
      d="M10.667 11.333a.605.605 0 0 1-.467-.2L7.533 8.467a.644.644 0 0 1 0-.934.644.644 0 0 1 .934 0l2.666 2.667a.644.644 0 0 1 0 .933.605.605 0 0 1-.466.2Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgTime;
