/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgToolsFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M5.95 3C3.217 3 1 5.268 1 8.063c0 .193.1.376.261.478a.54.54 0 0 0 .537.024l1.763-.9c.478.601 1.196.96 1.973.96h2.28c.752 0 1.443-.436 1.78-1.125H10.9c0 .622.492 1.125 1.1 1.125.608 0 1.1-.503 1.1-1.125V4.125C13.1 3.503 12.608 3 12 3c-.608 0-1.1.503-1.1 1.125H9.59A1.988 1.988 0 0 0 7.81 3H5.95Zm-1.1 6.75-.44 9.004C4.352 19.977 5.304 21 6.5 21c1.196 0 2.148-1.023 2.09-2.246L8.15 9.75h-3.3Zm10.526 11.018.711-2.183c.1-.31.526-.31.626 0l.711 2.183a.333.333 0 0 0 .313.232h3.613c.91 0 1.65-.756 1.65-1.687V14.25h-9.9v5.063c0 .931.74 1.687 1.65 1.687h.313c.14 0 .268-.091.313-.232Zm-1.296-9.436a2.274 2.274 0 0 0-.98 1.793H23a2.264 2.264 0 0 0-.98-1.793l-2.238-1.526a.458.458 0 0 0-.082-.042V4.688C19.7 3.756 18.96 3 18.05 3c-.91 0-1.65.756-1.65 1.688v5.08a.306.306 0 0 0-.082.042l-2.238 1.522Zm3.97-6.082a.556.556 0 0 1-.55-.562c0-.311.246-.563.55-.563.304 0 .55.252.55.563 0 .31-.246.562-.55.562Z"
    />
  </SvgIcon>
);
export default SvgToolsFill;
