/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgTrash = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.667 1.65c-.171 0-.342.071-.472.208a.787.787 0 0 0-.212.542v.75h4.034V2.4a.786.786 0 0 0-.212-.542.652.652 0 0 0-.472-.208H6.667Zm4.65 1.5V2.4c0-.534-.202-1.052-.57-1.438A1.952 1.952 0 0 0 9.333.35H6.667c-.537 0-1.045.224-1.414.612-.368.386-.57.904-.57 1.438v.75H2a.65.65 0 1 0 0 1.3h.683v9.15c0 .534.202 1.052.57 1.438.37.388.877.612 1.414.612h6.666c.537 0 1.045-.224 1.414-.612.368-.386.57-.904.57-1.438V4.45H14a.65.65 0 1 0 0-1.3h-2.683Zm-7.334 1.3v9.15c0 .209.08.403.212.542.13.137.3.208.472.208h6.666c.171 0 .342-.07.472-.208a.786.786 0 0 0 .212-.542V4.45H3.983Zm2.684 2.2a.65.65 0 0 1 .65.65v4.2a.65.65 0 1 1-1.3 0V7.3a.65.65 0 0 1 .65-.65Zm2.666 0a.65.65 0 0 1 .65.65v4.2a.65.65 0 1 1-1.3 0V7.3a.65.65 0 0 1 .65-.65Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgTrash;
