/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgTwitter = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M16 2.56a6.792 6.792 0 0 1-1.888.512 3.304 3.304 0 0 0 1.448-1.816 6.568 6.568 0 0 1-2.088.8 3.28 3.28 0 0 0-5.6 2.992 9.312 9.312 0 0 1-6.76-3.432 3.328 3.328 0 0 0-.44 1.656A3.272 3.272 0 0 0 2.128 6 3.24 3.24 0 0 1 .64 5.592v.04a3.28 3.28 0 0 0 2.64 3.2 3.144 3.144 0 0 1-.88.136 3.92 3.92 0 0 1-.616-.056 3.288 3.288 0 0 0 3.064 2.272A6.576 6.576 0 0 1 0 12.544a9.256 9.256 0 0 0 5.032 1.48A9.271 9.271 0 0 0 14.4 4.68v-.424A6.743 6.743 0 0 0 16 2.56Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgTwitter;
