/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgTwitter = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="M24 3.84c-.902.392-1.856.65-2.832.769a4.956 4.956 0 0 0 2.172-2.724 9.852 9.852 0 0 1-3.132 1.2 4.92 4.92 0 0 0-8.4 4.488 13.968 13.968 0 0 1-10.14-5.148 4.992 4.992 0 0 0-.66 2.484A4.908 4.908 0 0 0 3.192 9 4.86 4.86 0 0 1 .96 8.389v.06a4.92 4.92 0 0 0 3.96 4.8c-.428.13-.873.199-1.32.204a5.877 5.877 0 0 1-.924-.084 4.932 4.932 0 0 0 4.596 3.408A9.864 9.864 0 0 1 0 18.817a13.884 13.884 0 0 0 7.548 2.22A13.908 13.908 0 0 0 21.6 7.02v-.636A10.116 10.116 0 0 0 24 3.84Z"
      fill="#B8BDBF"
    />
  </SvgIcon>
);
export default SvgTwitter;
