/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgUnCheckedRadio = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    xmlns="http://www.w3.org/2000/svg"
    className="un-checked-radio_svg__c-PJLV un-checked-radio_svg__c-PJLV-fUxEU-size-lg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <circle cx={12} cy={12} r={12} fill="#EEF1F4" />
  </SvgIcon>
);
export default SvgUnCheckedRadio;
