/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgUserFill = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    width={24}
    height={24}
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fill="#000"
      fillRule="nonzero"
      d="M12 11.5c2.683 0 4.857-2.127 4.857-4.75S14.683 2 12 2C9.317 2 7.143 4.127 7.143 6.75S9.317 11.5 12 11.5Zm-1.734 1.781c-3.738 0-6.766 2.962-6.766 6.617 0 .608.505 1.102 1.127 1.102h14.746c.622 0 1.127-.494 1.127-1.102 0-3.655-3.028-6.617-6.766-6.617h-3.468Z"
    />
  </SvgIcon>
);
export default SvgUserFill;
