/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgWalletConnect = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="M4.913 7.374c3.914-3.832 10.26-3.832 14.174 0l.47.461a.483.483 0 0 1 0 .694l-1.61 1.578a.254.254 0 0 1-.355 0l-.648-.635c-2.73-2.673-7.157-2.673-9.888 0l-.694.68a.254.254 0 0 1-.354 0L4.396 8.574a.483.483 0 0 1 0-.694l.517-.506Zm17.506 3.263 1.434 1.404a.483.483 0 0 1 0 .694l-6.466 6.331a.509.509 0 0 1-.709 0l-4.59-4.493a.127.127 0 0 0-.176 0l-4.59 4.493a.509.509 0 0 1-.709 0L.147 12.735a.483.483 0 0 1 0-.694l1.434-1.404a.509.509 0 0 1 .709 0l4.59 4.493a.127.127 0 0 0 .176 0l4.59-4.493a.509.509 0 0 1 .708 0l4.59 4.493a.127.127 0 0 0 .177 0l4.59-4.493a.509.509 0 0 1 .708 0Z"
      fill="#B8BDBF"
    />
  </SvgIcon>
);
export default SvgWalletConnect;
