/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgWalletconnect = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={css}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      d="M3.276 4.916c2.609-2.555 6.84-2.555 9.449 0l.314.307c.13.128.13.335 0 .463l-1.075 1.052a.17.17 0 0 1-.236 0l-.432-.423c-1.82-1.783-4.772-1.783-6.592 0l-.463.453a.17.17 0 0 1-.236 0L2.931 5.716a.322.322 0 0 1 0-.463l.345-.337Zm11.67 2.175.956.936c.13.128.13.335 0 .463l-4.31 4.22a.34.34 0 0 1-.473 0l-3.06-2.995a.085.085 0 0 0-.118 0l-3.06 2.996a.34.34 0 0 1-.472 0L.098 8.49a.322.322 0 0 1 0-.463l.956-.936a.34.34 0 0 1 .472 0l3.06 2.996a.085.085 0 0 0 .118 0l3.06-2.996a.34.34 0 0 1 .472 0l3.06 2.996a.085.085 0 0 0 .118 0l3.06-2.996a.34.34 0 0 1 .472 0Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgWalletconnect;
