/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgWonder = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={19}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.806 5.003c-.015.076-.076.136-.167.166a6.525 6.525 0 0 0-4.428 4.413.222.222 0 0 1-.211.167.222.222 0 0 1-.212-.167A6.468 6.468 0 0 0 7.36 5.17c-.09-.03-.151-.09-.166-.166h-.015v-.06h.015c.015-.076.075-.136.166-.167A6.468 6.468 0 0 0 11.788.364.222.222 0 0 1 12 .197c.09 0 .181.06.211.167a6.468 6.468 0 0 0 4.428 4.412c.091.03.152.091.167.167h.015v.06h-.015Zm-16.473.03h-.09c-.182 0-.303.197-.212.348l3.642 6.302 3.642 6.302a.24.24 0 0 0 .408 0l2.66-4.625c.242-.423.257-.952.015-1.375A13.619 13.619 0 0 0 .333 5.033Zm23.425 0h-.091c-4.353.59-8.055 3.25-10.08 6.967-.242.423-.227.952.015 1.376L16.277 18a.24.24 0 0 0 .408 0l3.642-6.302 3.642-6.302a.244.244 0 0 0-.211-.363Z"
      fill="currentColor"
    />
  </SvgIcon>
);
export default SvgWonder;
