/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgWonderColor = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={18}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.806 4.806c-.015.076-.076.136-.166.166a6.525 6.525 0 0 0-4.428 4.413.222.222 0 0 1-.212.166.222.222 0 0 1-.211-.166A6.468 6.468 0 0 0 7.36 4.972c-.09-.03-.15-.09-.166-.166H7.18v-.06h.015c.015-.076.076-.137.166-.167A6.468 6.468 0 0 0 11.79.166.222.222 0 0 1 12 0c.09 0 .181.06.212.166A6.468 6.468 0 0 0 16.64 4.58c.09.03.15.09.166.167h.015v.06h-.015Zm-16.473.03h-.09c-.182 0-.303.196-.212.347l3.642 6.302 3.642 6.303a.24.24 0 0 0 .408 0l2.66-4.625c.242-.423.257-.952.015-1.375A13.62 13.62 0 0 0 .333 4.836Zm23.425 0h-.091c-4.353.59-8.055 3.249-10.08 6.967-.242.423-.227.952.015 1.375l2.675 4.625a.24.24 0 0 0 .408 0l3.642-6.303 3.642-6.302a.244.244 0 0 0-.212-.362Z"
      fill="url(#Wonder_Color_svg__a)"
    />
    <defs>
      <linearGradient
        id="Wonder_Color_svg__a"
        x1={20.909}
        y1={17.916}
        x2={20.507}
        y2={0}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#CBF" />
        <stop offset={0.474} stopColor="#7427FF" />
        <stop offset={1} stopColor="#00BAFF" />
      </linearGradient>
    </defs>
  </SvgIcon>
);
export default SvgWonderColor;
