/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  '& path': {
    stroke: 'none',
  },
};
export const SvgWorking = (props: SvgIconProps) => (
  <SvgIcon
    width={16}
    height={16}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 16 16"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.114 5.848a5.51 5.51 0 0 0-9.328-1.404l1.73-.188a1 1 0 1 1 .216 1.988l-3.83.416a1 1 0 0 1-1.096-.837L.204 2.017a1 1 0 1 1 1.975-.313l.206 1.301A7.51 7.51 0 0 1 14.96 5.08a1 1 0 0 1-1.846.769ZM1.632 9.544a1 1 0 0 1 1.307.539 5.51 5.51 0 0 0 9.223 1.527l-1.546.086a1 1 0 0 1-.111-1.997l3.669-.205a1 1 0 0 1 1.034.79l.764 3.595a1 1 0 0 1-1.957.416l-.302-1.422a7.51 7.51 0 0 1-12.62-2.022 1 1 0 0 1 .539-1.307Z"
      fill="#000"
    />
  </SvgIcon>
);
export default SvgWorking;
