/* eslint-disable react/display-name */
/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE
/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgWrite = (props: SvgIconProps) => (
  <SvgIcon
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    style={{
      fillRule: 'evenodd',
      clipRule: 'evenodd',
      strokeLinejoin: 'round',
      strokeMiterlimit: 2,
    }}
    viewBox="0 0 24 24"
    css={{ ...css, ...(props.css ?? {}) }}
    {...props}
  >
    <path
      d="M190.107 167.501h179.172v160.79H190.107z"
      style={{
        fill: 'none',
      }}
      transform="matrix(.13395 0 0 .14926 -25.465 -25.002)"
    />
    <g transform="matrix(.04167 0 0 .04167 0 1.333)">
      <clipPath id="write_svg__a">
        <path d="M0 0h576v512H0z" />
      </clipPath>
      <g clipPath="url(#write_svg__a)">
        <path
          d="M429.8 39.6c-9.4-9.4-24.6-9.4-33.9 0L341 94.4l76.6 76.6 54.8-54.8c9.4-9.4 9.4-24.6 0-33.9l-42.6-42.7ZM83.1 352.4C75.5 360 70 369.3 67 379.6l-27.4 92.8 92.8-27.3c10.3-3 19.6-8.6 27.2-16.1L395 193.6 318.4 117 83.1 352.4ZM373.2 17c21.9-21.9 57.3-21.9 79.2 0L495 59.6c21.9 21.9 21.9 57.3 0 79.2L182.3 451.6c-11.4 11.4-25.4 19.7-40.8 24.2l-121 35.6c-5.6 1.7-11.7.1-15.8-4-4.1-4.1-5.7-10.2-4-15.8l35.6-121c4.5-15.4 12.9-29.4 24.2-40.8L373.2 17ZM240 480h320c8.8 0 16 7.2 16 16s-7.2 16-16 16H240c-8.8 0-16-7.2-16-16s7.2-16 16-16Z"
          style={{
            fillRule: 'nonzero',
          }}
        />
      </g>
    </g>
  </SvgIcon>
);
export default SvgWrite;
