/* eslint-disable react/display-name */

/* eslint-disable import/order */
// DO NOT EDIT - GENERATED FILE

/* exported and autogenerated using SVGR from https://www.figma.com/file/ZHiNW0Wf2bj2VHVIqpjMuh/Design-Library?node-id=495%3A629 */
import { SvgIcon, SvgIconProps } from '../../ui/SvgIcon/SvgIcon';
const css = {
  // '& path': { stroke: 'none' }
  // '& path': { stroke: 'none' }
};
export const SvgYearn = (props: SvgIconProps) => (
  <SvgIcon
    width={24}
    height={24}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    css={{ ...css, ...(props.css ?? {}) }}
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M4.019 1.42 2.65 2.82l3.335 3.413L9.32 9.646v6.356h3.874V9.646l3.335-3.413 3.334-3.413-1.377-1.41L17.108 0l-2.906 2.973c-1.598 1.636-2.923 2.974-2.945 2.974-.022 0-1.343-1.334-2.935-2.963A301.087 301.087 0 0 0 5.407.02c-.011 0-.636.63-1.388 1.4ZM2.586 9.387c-.485.86-.932 2.39-1.055 3.614-.06.603-.028 1.92.061 2.51.842 5.535 5.95 9.296 11.324 8.34 3.543-.63 6.457-3.188 7.59-6.664.372-1.143.493-1.917.494-3.167.001-1.354-.15-2.253-.585-3.495-.15-.426-.534-1.267-.579-1.267-.018 0-.687.669-1.486 1.487-1.343 1.375-1.45 1.496-1.432 1.604.011.065.05.252.085.417.104.479.145 1.126.104 1.666a5.673 5.673 0 0 1-.277 1.456c-.541 1.73-1.975 3.211-3.687 3.81-.654.229-1.021.285-1.866.287-.858.002-1.182-.045-1.847-.266-1.81-.603-3.286-2.158-3.817-4.024-.173-.605-.223-.992-.22-1.716.002-.673.023-.845.199-1.635.014-.064-.307-.414-1.455-1.588L2.664 9.25l-.078.137Z"
      fill="#B8BDBF"
    />
  </SvgIcon>
);
export default SvgYearn;
