/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Boolean_comparison_exp: {},
  Int_comparison_exp: {},
  String_comparison_exp: {},
  bigint: 'String',
  bigint_comparison_exp: {
    _eq: 'bigint',
    _gt: 'bigint',
    _gte: 'bigint',
    _in: 'bigint',
    _lt: 'bigint',
    _lte: 'bigint',
    _neq: 'bigint',
    _nin: 'bigint',
  },
  citext: 'String',
  citext_comparison_exp: {
    _eq: 'citext',
    _gt: 'citext',
    _gte: 'citext',
    _ilike: 'citext',
    _in: 'citext',
    _iregex: 'citext',
    _like: 'citext',
    _lt: 'citext',
    _lte: 'citext',
    _neq: 'citext',
    _nilike: 'citext',
    _nin: 'citext',
    _niregex: 'citext',
    _nlike: 'citext',
    _nregex: 'citext',
    _nsimilar: 'citext',
    _regex: 'citext',
    _similar: 'citext',
  },
  colinks_give_count_bool_exp: {
    _and: 'colinks_give_count_bool_exp',
    _not: 'colinks_give_count_bool_exp',
    _or: 'colinks_give_count_bool_exp',
    gives: 'bigint_comparison_exp',
    gives_last_24_hours: 'bigint_comparison_exp',
    gives_last_30_days: 'bigint_comparison_exp',
    gives_last_7_days: 'bigint_comparison_exp',
    skill: 'citext_comparison_exp',
  },
  colinks_give_count_order_by: {
    gives: 'order_by',
    gives_last_24_hours: 'order_by',
    gives_last_30_days: 'order_by',
    gives_last_7_days: 'order_by',
    skill: 'order_by',
  },
  colinks_give_count_select_column: true,
  colinks_give_count_stream_cursor_input: {
    initial_value: 'colinks_give_count_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  colinks_give_count_stream_cursor_value_input: {
    gives: 'bigint',
    gives_last_24_hours: 'bigint',
    gives_last_30_days: 'bigint',
    gives_last_7_days: 'bigint',
    skill: 'citext',
  },
  colinks_gives_aggregate_bool_exp: {
    count: 'colinks_gives_aggregate_bool_exp_count',
  },
  colinks_gives_aggregate_bool_exp_count: {
    arguments: 'colinks_gives_select_column',
    filter: 'colinks_gives_bool_exp',
    predicate: 'Int_comparison_exp',
  },
  colinks_gives_aggregate_fields: {
    count: {
      columns: 'colinks_gives_select_column',
    },
  },
  colinks_gives_aggregate_order_by: {
    avg: 'colinks_gives_avg_order_by',
    count: 'order_by',
    max: 'colinks_gives_max_order_by',
    min: 'colinks_gives_min_order_by',
    stddev: 'colinks_gives_stddev_order_by',
    stddev_pop: 'colinks_gives_stddev_pop_order_by',
    stddev_samp: 'colinks_gives_stddev_samp_order_by',
    sum: 'colinks_gives_sum_order_by',
    var_pop: 'colinks_gives_var_pop_order_by',
    var_samp: 'colinks_gives_var_samp_order_by',
    variance: 'colinks_gives_variance_order_by',
  },
  colinks_gives_avg_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_bool_exp: {
    _and: 'colinks_gives_bool_exp',
    _not: 'colinks_gives_bool_exp',
    _or: 'colinks_gives_bool_exp',
    activity_id: 'bigint_comparison_exp',
    attestation_uid: 'String_comparison_exp',
    cast_hash: 'String_comparison_exp',
    created_at: 'timestamptz_comparison_exp',
    give_skill: 'skills_bool_exp',
    giver_profile_public: 'profiles_public_bool_exp',
    id: 'Int_comparison_exp',
    profile_id: 'bigint_comparison_exp',
    skill: 'citext_comparison_exp',
    target_profile_id: 'bigint_comparison_exp',
    target_profile_public: 'profiles_public_bool_exp',
    updated_at: 'timestamptz_comparison_exp',
  },
  colinks_gives_max_order_by: {
    activity_id: 'order_by',
    attestation_uid: 'order_by',
    cast_hash: 'order_by',
    created_at: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    skill: 'order_by',
    target_profile_id: 'order_by',
    updated_at: 'order_by',
  },
  colinks_gives_min_order_by: {
    activity_id: 'order_by',
    attestation_uid: 'order_by',
    cast_hash: 'order_by',
    created_at: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    skill: 'order_by',
    target_profile_id: 'order_by',
    updated_at: 'order_by',
  },
  colinks_gives_order_by: {
    activity_id: 'order_by',
    attestation_uid: 'order_by',
    cast_hash: 'order_by',
    created_at: 'order_by',
    give_skill: 'skills_order_by',
    giver_profile_public: 'profiles_public_order_by',
    id: 'order_by',
    profile_id: 'order_by',
    skill: 'order_by',
    target_profile_id: 'order_by',
    target_profile_public: 'profiles_public_order_by',
    updated_at: 'order_by',
  },
  colinks_gives_select_column: true,
  colinks_gives_skill_count_bool_exp: {
    _and: 'colinks_gives_skill_count_bool_exp',
    _not: 'colinks_gives_skill_count_bool_exp',
    _or: 'colinks_gives_skill_count_bool_exp',
    gives: 'bigint_comparison_exp',
    gives_last_24_hours: 'bigint_comparison_exp',
    gives_last_30_days: 'bigint_comparison_exp',
    gives_last_7_days: 'bigint_comparison_exp',
    skill: 'citext_comparison_exp',
    skill_info: 'skills_bool_exp',
    target_profile_id: 'bigint_comparison_exp',
    target_profile_public: 'profiles_public_bool_exp',
  },
  colinks_gives_skill_count_order_by: {
    gives: 'order_by',
    gives_last_24_hours: 'order_by',
    gives_last_30_days: 'order_by',
    gives_last_7_days: 'order_by',
    skill: 'order_by',
    skill_info: 'skills_order_by',
    target_profile_id: 'order_by',
    target_profile_public: 'profiles_public_order_by',
  },
  colinks_gives_skill_count_select_column: true,
  colinks_gives_skill_count_stream_cursor_input: {
    initial_value: 'colinks_gives_skill_count_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  colinks_gives_skill_count_stream_cursor_value_input: {
    gives: 'bigint',
    gives_last_24_hours: 'bigint',
    gives_last_30_days: 'bigint',
    gives_last_7_days: 'bigint',
    skill: 'citext',
    target_profile_id: 'bigint',
  },
  colinks_gives_stddev_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_stddev_pop_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_stddev_samp_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_stream_cursor_input: {
    initial_value: 'colinks_gives_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  colinks_gives_stream_cursor_value_input: {
    activity_id: 'bigint',
    created_at: 'timestamptz',
    profile_id: 'bigint',
    skill: 'citext',
    target_profile_id: 'bigint',
    updated_at: 'timestamptz',
  },
  colinks_gives_sum_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_var_pop_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_var_samp_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  colinks_gives_variance_order_by: {
    activity_id: 'order_by',
    id: 'order_by',
    profile_id: 'order_by',
    target_profile_id: 'order_by',
  },
  cosouls: {
    held_links: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    held_links_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
  },
  cosouls_bool_exp: {
    _and: 'cosouls_bool_exp',
    _not: 'cosouls_bool_exp',
    _or: 'cosouls_bool_exp',
    address: 'citext_comparison_exp',
    checked_at: 'timestamptz_comparison_exp',
    created_at: 'timestamptz_comparison_exp',
    created_tx_hash: 'String_comparison_exp',
    held_links: 'link_holders_bool_exp',
    held_links_aggregate: 'link_holders_aggregate_bool_exp',
    id: 'Int_comparison_exp',
    link_holders: 'link_holders_bool_exp',
    link_holders_aggregate: 'link_holders_aggregate_bool_exp',
    pgive: 'Int_comparison_exp',
    profile_public: 'profiles_public_bool_exp',
    synced_at: 'timestamptz_comparison_exp',
    token_id: 'Int_comparison_exp',
    updated_at: 'timestamptz_comparison_exp',
  },
  cosouls_order_by: {
    address: 'order_by',
    checked_at: 'order_by',
    created_at: 'order_by',
    created_tx_hash: 'order_by',
    held_links_aggregate: 'link_holders_aggregate_order_by',
    id: 'order_by',
    link_holders_aggregate: 'link_holders_aggregate_order_by',
    pgive: 'order_by',
    profile_public: 'profiles_public_order_by',
    synced_at: 'order_by',
    token_id: 'order_by',
    updated_at: 'order_by',
  },
  cosouls_select_column: true,
  cosouls_stream_cursor_input: {
    initial_value: 'cosouls_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  cosouls_stream_cursor_value_input: {
    address: 'citext',
    checked_at: 'timestamptz',
    created_at: 'timestamptz',
    synced_at: 'timestamptz',
    updated_at: 'timestamptz',
  },
  cursor_ordering: true,
  farcaster_accounts_bool_exp: {
    _and: 'farcaster_accounts_bool_exp',
    _not: 'farcaster_accounts_bool_exp',
    _or: 'farcaster_accounts_bool_exp',
    bio_text: 'String_comparison_exp',
    created_at: 'timestamptz_comparison_exp',
    custody_address: 'String_comparison_exp',
    fid: 'bigint_comparison_exp',
    followers_count: 'Int_comparison_exp',
    following_count: 'Int_comparison_exp',
    name: 'String_comparison_exp',
    pfp_url: 'String_comparison_exp',
    profile_id: 'bigint_comparison_exp',
    profile_public: 'profiles_public_bool_exp',
    updated_at: 'timestamptz_comparison_exp',
    username: 'String_comparison_exp',
  },
  farcaster_accounts_order_by: {
    bio_text: 'order_by',
    created_at: 'order_by',
    custody_address: 'order_by',
    fid: 'order_by',
    followers_count: 'order_by',
    following_count: 'order_by',
    name: 'order_by',
    pfp_url: 'order_by',
    profile_id: 'order_by',
    profile_public: 'profiles_public_order_by',
    updated_at: 'order_by',
    username: 'order_by',
  },
  farcaster_accounts_select_column: true,
  farcaster_accounts_stream_cursor_input: {
    initial_value: 'farcaster_accounts_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  farcaster_accounts_stream_cursor_value_input: {
    created_at: 'timestamptz',
    fid: 'bigint',
    profile_id: 'bigint',
    updated_at: 'timestamptz',
  },
  github_accounts_bool_exp: {
    _and: 'github_accounts_bool_exp',
    _not: 'github_accounts_bool_exp',
    _or: 'github_accounts_bool_exp',
    profile_id: 'bigint_comparison_exp',
    username: 'String_comparison_exp',
  },
  github_accounts_order_by: {
    profile_id: 'order_by',
    username: 'order_by',
  },
  github_accounts_select_column: true,
  github_accounts_stream_cursor_input: {
    initial_value: 'github_accounts_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  github_accounts_stream_cursor_value_input: {
    profile_id: 'bigint',
  },
  link_holders_aggregate_bool_exp: {
    count: 'link_holders_aggregate_bool_exp_count',
  },
  link_holders_aggregate_bool_exp_count: {
    arguments: 'link_holders_select_column',
    filter: 'link_holders_bool_exp',
    predicate: 'Int_comparison_exp',
  },
  link_holders_aggregate_fields: {
    count: {
      columns: 'link_holders_select_column',
    },
  },
  link_holders_aggregate_order_by: {
    avg: 'link_holders_avg_order_by',
    count: 'order_by',
    max: 'link_holders_max_order_by',
    min: 'link_holders_min_order_by',
    stddev: 'link_holders_stddev_order_by',
    stddev_pop: 'link_holders_stddev_pop_order_by',
    stddev_samp: 'link_holders_stddev_samp_order_by',
    sum: 'link_holders_sum_order_by',
    var_pop: 'link_holders_var_pop_order_by',
    var_samp: 'link_holders_var_samp_order_by',
    variance: 'link_holders_variance_order_by',
  },
  link_holders_avg_order_by: {
    amount: 'order_by',
  },
  link_holders_bool_exp: {
    _and: 'link_holders_bool_exp',
    _not: 'link_holders_bool_exp',
    _or: 'link_holders_bool_exp',
    amount: 'Int_comparison_exp',
    holder: 'citext_comparison_exp',
    holder_cosoul: 'cosouls_bool_exp',
    holder_profile_public: 'profiles_public_bool_exp',
    target: 'citext_comparison_exp',
    target_cosoul: 'cosouls_bool_exp',
    target_profile_public: 'profiles_public_bool_exp',
    updated_at: 'timestamptz_comparison_exp',
  },
  link_holders_max_order_by: {
    amount: 'order_by',
    holder: 'order_by',
    target: 'order_by',
    updated_at: 'order_by',
  },
  link_holders_min_order_by: {
    amount: 'order_by',
    holder: 'order_by',
    target: 'order_by',
    updated_at: 'order_by',
  },
  link_holders_order_by: {
    amount: 'order_by',
    holder: 'order_by',
    holder_cosoul: 'cosouls_order_by',
    holder_profile_public: 'profiles_public_order_by',
    target: 'order_by',
    target_cosoul: 'cosouls_order_by',
    target_profile_public: 'profiles_public_order_by',
    updated_at: 'order_by',
  },
  link_holders_select_column: true,
  link_holders_stddev_order_by: {
    amount: 'order_by',
  },
  link_holders_stddev_pop_order_by: {
    amount: 'order_by',
  },
  link_holders_stddev_samp_order_by: {
    amount: 'order_by',
  },
  link_holders_stream_cursor_input: {
    initial_value: 'link_holders_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  link_holders_stream_cursor_value_input: {
    holder: 'citext',
    target: 'citext',
    updated_at: 'timestamptz',
  },
  link_holders_sum_order_by: {
    amount: 'order_by',
  },
  link_holders_var_pop_order_by: {
    amount: 'order_by',
  },
  link_holders_var_samp_order_by: {
    amount: 'order_by',
  },
  link_holders_variance_order_by: {
    amount: 'order_by',
  },
  order_by: true,
  profile_skills_aggregate_order_by: {
    avg: 'profile_skills_avg_order_by',
    count: 'order_by',
    max: 'profile_skills_max_order_by',
    min: 'profile_skills_min_order_by',
    stddev: 'profile_skills_stddev_order_by',
    stddev_pop: 'profile_skills_stddev_pop_order_by',
    stddev_samp: 'profile_skills_stddev_samp_order_by',
    sum: 'profile_skills_sum_order_by',
    var_pop: 'profile_skills_var_pop_order_by',
    var_samp: 'profile_skills_var_samp_order_by',
    variance: 'profile_skills_variance_order_by',
  },
  profile_skills_avg_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_bool_exp: {
    _and: 'profile_skills_bool_exp',
    _not: 'profile_skills_bool_exp',
    _or: 'profile_skills_bool_exp',
    profile_id: 'Int_comparison_exp',
    profile_public: 'profiles_public_bool_exp',
    skill: 'skills_bool_exp',
    skill_name: 'citext_comparison_exp',
  },
  profile_skills_max_order_by: {
    profile_id: 'order_by',
    skill_name: 'order_by',
  },
  profile_skills_min_order_by: {
    profile_id: 'order_by',
    skill_name: 'order_by',
  },
  profile_skills_order_by: {
    profile_id: 'order_by',
    profile_public: 'profiles_public_order_by',
    skill: 'skills_order_by',
    skill_name: 'order_by',
  },
  profile_skills_select_column: true,
  profile_skills_stddev_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_stddev_pop_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_stddev_samp_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_stream_cursor_input: {
    initial_value: 'profile_skills_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  profile_skills_stream_cursor_value_input: {
    skill_name: 'citext',
  },
  profile_skills_sum_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_var_pop_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_var_samp_order_by: {
    profile_id: 'order_by',
  },
  profile_skills_variance_order_by: {
    profile_id: 'order_by',
  },
  profiles_public: {
    colinks_given: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_given_aggregate: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives_aggregate: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    link_holder: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holder_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_target: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_target_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    profile_skills: {
      distinct_on: 'profile_skills_select_column',
      order_by: 'profile_skills_order_by',
      where: 'profile_skills_bool_exp',
    },
  },
  profiles_public_bool_exp: {
    _and: 'profiles_public_bool_exp',
    _not: 'profiles_public_bool_exp',
    _or: 'profiles_public_bool_exp',
    address: 'String_comparison_exp',
    avatar: 'String_comparison_exp',
    colinks_given: 'colinks_gives_bool_exp',
    colinks_given_aggregate: 'colinks_gives_aggregate_bool_exp',
    colinks_gives: 'colinks_gives_bool_exp',
    colinks_gives_aggregate: 'colinks_gives_aggregate_bool_exp',
    cosoul: 'cosouls_bool_exp',
    created_at: 'timestamp_comparison_exp',
    description: 'String_comparison_exp',
    farcaster_account: 'farcaster_accounts_bool_exp',
    id: 'bigint_comparison_exp',
    joined_colinks_at: 'timestamptz_comparison_exp',
    link_holder: 'link_holders_bool_exp',
    link_holder_aggregate: 'link_holders_aggregate_bool_exp',
    link_target: 'link_holders_bool_exp',
    link_target_aggregate: 'link_holders_aggregate_bool_exp',
    links: 'Int_comparison_exp',
    links_held: 'Int_comparison_exp',
    name: 'citext_comparison_exp',
    post_count: 'bigint_comparison_exp',
    post_count_last_30_days: 'bigint_comparison_exp',
    profile_skills: 'profile_skills_bool_exp',
    reputation_score: 'reputation_scores_bool_exp',
    website: 'String_comparison_exp',
  },
  profiles_public_order_by: {
    address: 'order_by',
    avatar: 'order_by',
    colinks_given_aggregate: 'colinks_gives_aggregate_order_by',
    colinks_gives_aggregate: 'colinks_gives_aggregate_order_by',
    cosoul: 'cosouls_order_by',
    created_at: 'order_by',
    description: 'order_by',
    farcaster_account: 'farcaster_accounts_order_by',
    id: 'order_by',
    joined_colinks_at: 'order_by',
    link_holder_aggregate: 'link_holders_aggregate_order_by',
    link_target_aggregate: 'link_holders_aggregate_order_by',
    links: 'order_by',
    links_held: 'order_by',
    name: 'order_by',
    post_count: 'order_by',
    post_count_last_30_days: 'order_by',
    profile_skills_aggregate: 'profile_skills_aggregate_order_by',
    reputation_score: 'reputation_scores_order_by',
    website: 'order_by',
  },
  profiles_public_select_column: true,
  profiles_public_stream_cursor_input: {
    initial_value: 'profiles_public_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  profiles_public_stream_cursor_value_input: {
    created_at: 'timestamp',
    id: 'bigint',
    joined_colinks_at: 'timestamptz',
    name: 'citext',
    post_count: 'bigint',
    post_count_last_30_days: 'bigint',
  },
  query_root: {
    colinks_give_count: {
      distinct_on: 'colinks_give_count_select_column',
      order_by: 'colinks_give_count_order_by',
      where: 'colinks_give_count_bool_exp',
    },
    colinks_gives: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives_aggregate: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives_by_pk: {},
    colinks_gives_skill_count: {
      distinct_on: 'colinks_gives_skill_count_select_column',
      order_by: 'colinks_gives_skill_count_order_by',
      where: 'colinks_gives_skill_count_bool_exp',
    },
    cosouls: {
      distinct_on: 'cosouls_select_column',
      order_by: 'cosouls_order_by',
      where: 'cosouls_bool_exp',
    },
    cosouls_by_pk: {},
    farcaster_accounts: {
      distinct_on: 'farcaster_accounts_select_column',
      order_by: 'farcaster_accounts_order_by',
      where: 'farcaster_accounts_bool_exp',
    },
    farcaster_accounts_by_pk: {
      profile_id: 'bigint',
    },
    github_accounts: {
      distinct_on: 'github_accounts_select_column',
      order_by: 'github_accounts_order_by',
      where: 'github_accounts_bool_exp',
    },
    github_accounts_by_pk: {
      profile_id: 'bigint',
    },
    link_holders: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders_by_pk: {
      holder: 'citext',
      target: 'citext',
    },
    price_per_share: {},
    profile_skills: {
      distinct_on: 'profile_skills_select_column',
      order_by: 'profile_skills_order_by',
      where: 'profile_skills_bool_exp',
    },
    profile_skills_by_pk: {
      skill_name: 'citext',
    },
    profiles_public: {
      distinct_on: 'profiles_public_select_column',
      order_by: 'profiles_public_order_by',
      where: 'profiles_public_bool_exp',
    },
    reputation_scores: {
      distinct_on: 'reputation_scores_select_column',
      order_by: 'reputation_scores_order_by',
      where: 'reputation_scores_bool_exp',
    },
    reputation_scores_by_pk: {
      profile_id: 'bigint',
    },
    skills: {
      distinct_on: 'skills_select_column',
      order_by: 'skills_order_by',
      where: 'skills_bool_exp',
    },
    skills_by_pk: {
      name: 'citext',
    },
    twitter_accounts: {
      distinct_on: 'twitter_accounts_select_column',
      order_by: 'twitter_accounts_order_by',
      where: 'twitter_accounts_bool_exp',
    },
    twitter_accounts_by_pk: {},
  },
  reputation_scores_bool_exp: {
    _and: 'reputation_scores_bool_exp',
    _not: 'reputation_scores_bool_exp',
    _or: 'reputation_scores_bool_exp',
    colinks_engagement_score: 'Int_comparison_exp',
    created_at: 'timestamptz_comparison_exp',
    email_score: 'Int_comparison_exp',
    github_score: 'Int_comparison_exp',
    invite_score: 'Int_comparison_exp',
    linkedin_score: 'Int_comparison_exp',
    links_score: 'Int_comparison_exp',
    pgive_score: 'Int_comparison_exp',
    poap_score: 'Int_comparison_exp',
    profile_id: 'bigint_comparison_exp',
    total_score: 'Int_comparison_exp',
    twitter_score: 'Int_comparison_exp',
    updated_at: 'timestamptz_comparison_exp',
  },
  reputation_scores_order_by: {
    colinks_engagement_score: 'order_by',
    created_at: 'order_by',
    email_score: 'order_by',
    github_score: 'order_by',
    invite_score: 'order_by',
    linkedin_score: 'order_by',
    links_score: 'order_by',
    pgive_score: 'order_by',
    poap_score: 'order_by',
    profile_id: 'order_by',
    total_score: 'order_by',
    twitter_score: 'order_by',
    updated_at: 'order_by',
  },
  reputation_scores_select_column: true,
  reputation_scores_stream_cursor_input: {
    initial_value: 'reputation_scores_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  reputation_scores_stream_cursor_value_input: {
    created_at: 'timestamptz',
    profile_id: 'bigint',
    updated_at: 'timestamptz',
  },
  skills_bool_exp: {
    _and: 'skills_bool_exp',
    _not: 'skills_bool_exp',
    _or: 'skills_bool_exp',
    count: 'Int_comparison_exp',
    created_at: 'timestamptz_comparison_exp',
    hidden: 'Boolean_comparison_exp',
    name: 'citext_comparison_exp',
    profile_skills: 'profile_skills_bool_exp',
    updated_at: 'timestamptz_comparison_exp',
  },
  skills_order_by: {
    count: 'order_by',
    created_at: 'order_by',
    hidden: 'order_by',
    name: 'order_by',
    profile_skills: 'profile_skills_order_by',
    updated_at: 'order_by',
  },
  skills_select_column: true,
  skills_stream_cursor_input: {
    initial_value: 'skills_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  skills_stream_cursor_value_input: {
    created_at: 'timestamptz',
    name: 'citext',
    updated_at: 'timestamptz',
  },
  subscription_root: {
    colinks_give_count: {
      distinct_on: 'colinks_give_count_select_column',
      order_by: 'colinks_give_count_order_by',
      where: 'colinks_give_count_bool_exp',
    },
    colinks_give_count_stream: {
      cursor: 'colinks_give_count_stream_cursor_input',
      where: 'colinks_give_count_bool_exp',
    },
    colinks_gives: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives_aggregate: {
      distinct_on: 'colinks_gives_select_column',
      order_by: 'colinks_gives_order_by',
      where: 'colinks_gives_bool_exp',
    },
    colinks_gives_by_pk: {},
    colinks_gives_skill_count: {
      distinct_on: 'colinks_gives_skill_count_select_column',
      order_by: 'colinks_gives_skill_count_order_by',
      where: 'colinks_gives_skill_count_bool_exp',
    },
    colinks_gives_skill_count_stream: {
      cursor: 'colinks_gives_skill_count_stream_cursor_input',
      where: 'colinks_gives_skill_count_bool_exp',
    },
    colinks_gives_stream: {
      cursor: 'colinks_gives_stream_cursor_input',
      where: 'colinks_gives_bool_exp',
    },
    cosouls: {
      distinct_on: 'cosouls_select_column',
      order_by: 'cosouls_order_by',
      where: 'cosouls_bool_exp',
    },
    cosouls_by_pk: {},
    cosouls_stream: {
      cursor: 'cosouls_stream_cursor_input',
      where: 'cosouls_bool_exp',
    },
    farcaster_accounts: {
      distinct_on: 'farcaster_accounts_select_column',
      order_by: 'farcaster_accounts_order_by',
      where: 'farcaster_accounts_bool_exp',
    },
    farcaster_accounts_by_pk: {
      profile_id: 'bigint',
    },
    farcaster_accounts_stream: {
      cursor: 'farcaster_accounts_stream_cursor_input',
      where: 'farcaster_accounts_bool_exp',
    },
    github_accounts: {
      distinct_on: 'github_accounts_select_column',
      order_by: 'github_accounts_order_by',
      where: 'github_accounts_bool_exp',
    },
    github_accounts_by_pk: {
      profile_id: 'bigint',
    },
    github_accounts_stream: {
      cursor: 'github_accounts_stream_cursor_input',
      where: 'github_accounts_bool_exp',
    },
    link_holders: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders_aggregate: {
      distinct_on: 'link_holders_select_column',
      order_by: 'link_holders_order_by',
      where: 'link_holders_bool_exp',
    },
    link_holders_by_pk: {
      holder: 'citext',
      target: 'citext',
    },
    link_holders_stream: {
      cursor: 'link_holders_stream_cursor_input',
      where: 'link_holders_bool_exp',
    },
    profile_skills: {
      distinct_on: 'profile_skills_select_column',
      order_by: 'profile_skills_order_by',
      where: 'profile_skills_bool_exp',
    },
    profile_skills_by_pk: {
      skill_name: 'citext',
    },
    profile_skills_stream: {
      cursor: 'profile_skills_stream_cursor_input',
      where: 'profile_skills_bool_exp',
    },
    profiles_public: {
      distinct_on: 'profiles_public_select_column',
      order_by: 'profiles_public_order_by',
      where: 'profiles_public_bool_exp',
    },
    profiles_public_stream: {
      cursor: 'profiles_public_stream_cursor_input',
      where: 'profiles_public_bool_exp',
    },
    reputation_scores: {
      distinct_on: 'reputation_scores_select_column',
      order_by: 'reputation_scores_order_by',
      where: 'reputation_scores_bool_exp',
    },
    reputation_scores_by_pk: {
      profile_id: 'bigint',
    },
    reputation_scores_stream: {
      cursor: 'reputation_scores_stream_cursor_input',
      where: 'reputation_scores_bool_exp',
    },
    skills: {
      distinct_on: 'skills_select_column',
      order_by: 'skills_order_by',
      where: 'skills_bool_exp',
    },
    skills_by_pk: {
      name: 'citext',
    },
    skills_stream: {
      cursor: 'skills_stream_cursor_input',
      where: 'skills_bool_exp',
    },
    twitter_accounts: {
      distinct_on: 'twitter_accounts_select_column',
      order_by: 'twitter_accounts_order_by',
      where: 'twitter_accounts_bool_exp',
    },
    twitter_accounts_by_pk: {},
    twitter_accounts_stream: {
      cursor: 'twitter_accounts_stream_cursor_input',
      where: 'twitter_accounts_bool_exp',
    },
  },
  timestamp: 'String',
  timestamp_comparison_exp: {
    _eq: 'timestamp',
    _gt: 'timestamp',
    _gte: 'timestamp',
    _in: 'timestamp',
    _lt: 'timestamp',
    _lte: 'timestamp',
    _neq: 'timestamp',
    _nin: 'timestamp',
  },
  timestamptz: 'String',
  timestamptz_comparison_exp: {
    _eq: 'timestamptz',
    _gt: 'timestamptz',
    _gte: 'timestamptz',
    _in: 'timestamptz',
    _lt: 'timestamptz',
    _lte: 'timestamptz',
    _neq: 'timestamptz',
    _nin: 'timestamptz',
  },
  twitter_accounts_bool_exp: {
    _and: 'twitter_accounts_bool_exp',
    _not: 'twitter_accounts_bool_exp',
    _or: 'twitter_accounts_bool_exp',
    id: 'String_comparison_exp',
    profile_id: 'Int_comparison_exp',
    username: 'String_comparison_exp',
  },
  twitter_accounts_order_by: {
    id: 'order_by',
    profile_id: 'order_by',
    username: 'order_by',
  },
  twitter_accounts_select_column: true,
  twitter_accounts_stream_cursor_input: {
    initial_value: 'twitter_accounts_stream_cursor_value_input',
    ordering: 'cursor_ordering',
  },
  twitter_accounts_stream_cursor_value_input: {},
};

export const ReturnTypes: Record<string, any> = {
  cached: {
    ttl: 'Int',
    refresh: 'Boolean',
  },
  colinks_give_count: {
    gives: 'bigint',
    gives_last_24_hours: 'bigint',
    gives_last_30_days: 'bigint',
    gives_last_7_days: 'bigint',
    skill: 'citext',
  },
  colinks_gives: {
    activity_id: 'bigint',
    attestation_uid: 'String',
    cast_hash: 'String',
    created_at: 'timestamptz',
    give_skill: 'skills',
    giver_profile_public: 'profiles_public',
    id: 'Int',
    profile_id: 'bigint',
    skill: 'citext',
    target_profile_id: 'bigint',
    target_profile_public: 'profiles_public',
    updated_at: 'timestamptz',
  },
  colinks_gives_aggregate: {
    aggregate: 'colinks_gives_aggregate_fields',
    nodes: 'colinks_gives',
  },
  colinks_gives_aggregate_fields: {
    avg: 'colinks_gives_avg_fields',
    count: 'Int',
    max: 'colinks_gives_max_fields',
    min: 'colinks_gives_min_fields',
    stddev: 'colinks_gives_stddev_fields',
    stddev_pop: 'colinks_gives_stddev_pop_fields',
    stddev_samp: 'colinks_gives_stddev_samp_fields',
    sum: 'colinks_gives_sum_fields',
    var_pop: 'colinks_gives_var_pop_fields',
    var_samp: 'colinks_gives_var_samp_fields',
    variance: 'colinks_gives_variance_fields',
  },
  colinks_gives_avg_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_max_fields: {
    activity_id: 'bigint',
    attestation_uid: 'String',
    cast_hash: 'String',
    created_at: 'timestamptz',
    id: 'Int',
    profile_id: 'bigint',
    skill: 'citext',
    target_profile_id: 'bigint',
    updated_at: 'timestamptz',
  },
  colinks_gives_min_fields: {
    activity_id: 'bigint',
    attestation_uid: 'String',
    cast_hash: 'String',
    created_at: 'timestamptz',
    id: 'Int',
    profile_id: 'bigint',
    skill: 'citext',
    target_profile_id: 'bigint',
    updated_at: 'timestamptz',
  },
  colinks_gives_skill_count: {
    gives: 'bigint',
    gives_last_24_hours: 'bigint',
    gives_last_30_days: 'bigint',
    gives_last_7_days: 'bigint',
    skill: 'citext',
    skill_info: 'skills',
    target_profile_id: 'bigint',
    target_profile_public: 'profiles_public',
  },
  colinks_gives_stddev_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_stddev_pop_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_stddev_samp_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_sum_fields: {
    activity_id: 'bigint',
    id: 'Int',
    profile_id: 'bigint',
    target_profile_id: 'bigint',
  },
  colinks_gives_var_pop_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_var_samp_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  colinks_gives_variance_fields: {
    activity_id: 'Float',
    id: 'Float',
    profile_id: 'Float',
    target_profile_id: 'Float',
  },
  cosouls: {
    address: 'citext',
    checked_at: 'timestamptz',
    created_at: 'timestamptz',
    created_tx_hash: 'String',
    held_links: 'link_holders',
    held_links_aggregate: 'link_holders_aggregate',
    id: 'Int',
    link_holders: 'link_holders',
    link_holders_aggregate: 'link_holders_aggregate',
    pgive: 'Int',
    profile_public: 'profiles_public',
    synced_at: 'timestamptz',
    token_id: 'Int',
    updated_at: 'timestamptz',
  },
  farcaster_accounts: {
    bio_text: 'String',
    created_at: 'timestamptz',
    custody_address: 'String',
    fid: 'bigint',
    followers_count: 'Int',
    following_count: 'Int',
    name: 'String',
    pfp_url: 'String',
    profile_id: 'bigint',
    profile_public: 'profiles_public',
    updated_at: 'timestamptz',
    username: 'String',
  },
  github_accounts: {
    profile_id: 'bigint',
    username: 'String',
  },
  link_holders: {
    amount: 'Int',
    holder: 'citext',
    holder_cosoul: 'cosouls',
    holder_profile_public: 'profiles_public',
    target: 'citext',
    target_cosoul: 'cosouls',
    target_profile_public: 'profiles_public',
    updated_at: 'timestamptz',
  },
  link_holders_aggregate: {
    aggregate: 'link_holders_aggregate_fields',
    nodes: 'link_holders',
  },
  link_holders_aggregate_fields: {
    avg: 'link_holders_avg_fields',
    count: 'Int',
    max: 'link_holders_max_fields',
    min: 'link_holders_min_fields',
    stddev: 'link_holders_stddev_fields',
    stddev_pop: 'link_holders_stddev_pop_fields',
    stddev_samp: 'link_holders_stddev_samp_fields',
    sum: 'link_holders_sum_fields',
    var_pop: 'link_holders_var_pop_fields',
    var_samp: 'link_holders_var_samp_fields',
    variance: 'link_holders_variance_fields',
  },
  link_holders_avg_fields: {
    amount: 'Float',
  },
  link_holders_max_fields: {
    amount: 'Int',
    holder: 'citext',
    target: 'citext',
    updated_at: 'timestamptz',
  },
  link_holders_min_fields: {
    amount: 'Int',
    holder: 'citext',
    target: 'citext',
    updated_at: 'timestamptz',
  },
  link_holders_stddev_fields: {
    amount: 'Float',
  },
  link_holders_stddev_pop_fields: {
    amount: 'Float',
  },
  link_holders_stddev_samp_fields: {
    amount: 'Float',
  },
  link_holders_sum_fields: {
    amount: 'Int',
  },
  link_holders_var_pop_fields: {
    amount: 'Float',
  },
  link_holders_var_samp_fields: {
    amount: 'Float',
  },
  link_holders_variance_fields: {
    amount: 'Float',
  },
  profile_skills: {
    profile_id: 'Int',
    profile_public: 'profiles_public',
    skill: 'skills',
    skill_name: 'citext',
  },
  profiles_public: {
    address: 'String',
    avatar: 'String',
    colinks_given: 'colinks_gives',
    colinks_given_aggregate: 'colinks_gives_aggregate',
    colinks_gives: 'colinks_gives',
    colinks_gives_aggregate: 'colinks_gives_aggregate',
    cosoul: 'cosouls',
    created_at: 'timestamp',
    description: 'String',
    farcaster_account: 'farcaster_accounts',
    id: 'bigint',
    joined_colinks_at: 'timestamptz',
    link_holder: 'link_holders',
    link_holder_aggregate: 'link_holders_aggregate',
    link_target: 'link_holders',
    link_target_aggregate: 'link_holders_aggregate',
    links: 'Int',
    links_held: 'Int',
    name: 'citext',
    post_count: 'bigint',
    post_count_last_30_days: 'bigint',
    profile_skills: 'profile_skills',
    reputation_score: 'reputation_scores',
    website: 'String',
  },
  query_root: {
    colinks_give_count: 'colinks_give_count',
    colinks_gives: 'colinks_gives',
    colinks_gives_aggregate: 'colinks_gives_aggregate',
    colinks_gives_by_pk: 'colinks_gives',
    colinks_gives_skill_count: 'colinks_gives_skill_count',
    cosouls: 'cosouls',
    cosouls_by_pk: 'cosouls',
    farcaster_accounts: 'farcaster_accounts',
    farcaster_accounts_by_pk: 'farcaster_accounts',
    github_accounts: 'github_accounts',
    github_accounts_by_pk: 'github_accounts',
    link_holders: 'link_holders',
    link_holders_aggregate: 'link_holders_aggregate',
    link_holders_by_pk: 'link_holders',
    price_per_share: 'Float',
    profile_skills: 'profile_skills',
    profile_skills_by_pk: 'profile_skills',
    profiles_public: 'profiles_public',
    reputation_scores: 'reputation_scores',
    reputation_scores_by_pk: 'reputation_scores',
    skills: 'skills',
    skills_by_pk: 'skills',
    twitter_accounts: 'twitter_accounts',
    twitter_accounts_by_pk: 'twitter_accounts',
  },
  reputation_scores: {
    colinks_engagement_score: 'Int',
    created_at: 'timestamptz',
    email_score: 'Int',
    github_score: 'Int',
    invite_score: 'Int',
    linkedin_score: 'Int',
    links_score: 'Int',
    pgive_score: 'Int',
    poap_score: 'Int',
    profile_id: 'bigint',
    total_score: 'Int',
    twitter_score: 'Int',
    updated_at: 'timestamptz',
  },
  skills: {
    count: 'Int',
    created_at: 'timestamptz',
    hidden: 'Boolean',
    name: 'citext',
    profile_skills: 'profile_skills',
    updated_at: 'timestamptz',
  },
  subscription_root: {
    colinks_give_count: 'colinks_give_count',
    colinks_give_count_stream: 'colinks_give_count',
    colinks_gives: 'colinks_gives',
    colinks_gives_aggregate: 'colinks_gives_aggregate',
    colinks_gives_by_pk: 'colinks_gives',
    colinks_gives_skill_count: 'colinks_gives_skill_count',
    colinks_gives_skill_count_stream: 'colinks_gives_skill_count',
    colinks_gives_stream: 'colinks_gives',
    cosouls: 'cosouls',
    cosouls_by_pk: 'cosouls',
    cosouls_stream: 'cosouls',
    farcaster_accounts: 'farcaster_accounts',
    farcaster_accounts_by_pk: 'farcaster_accounts',
    farcaster_accounts_stream: 'farcaster_accounts',
    github_accounts: 'github_accounts',
    github_accounts_by_pk: 'github_accounts',
    github_accounts_stream: 'github_accounts',
    link_holders: 'link_holders',
    link_holders_aggregate: 'link_holders_aggregate',
    link_holders_by_pk: 'link_holders',
    link_holders_stream: 'link_holders',
    profile_skills: 'profile_skills',
    profile_skills_by_pk: 'profile_skills',
    profile_skills_stream: 'profile_skills',
    profiles_public: 'profiles_public',
    profiles_public_stream: 'profiles_public',
    reputation_scores: 'reputation_scores',
    reputation_scores_by_pk: 'reputation_scores',
    reputation_scores_stream: 'reputation_scores',
    skills: 'skills',
    skills_by_pk: 'skills',
    skills_stream: 'skills',
    twitter_accounts: 'twitter_accounts',
    twitter_accounts_by_pk: 'twitter_accounts',
    twitter_accounts_stream: 'twitter_accounts',
  },
  twitter_accounts: {
    id: 'String',
    profile_id: 'Int',
    username: 'String',
  },
};

export const Ops = {
  query: 'query_root' as const,
  subscription: 'subscription_root' as const,
};
