table:
  name: users
  schema: discord
object_relationships:
  - name: profile
    using:
      foreign_key_constraint_on: profile_id
insert_permissions:
  - role: discord-bot
    permission:
      check: {}
      columns:
        - profile_id
        - user_snowflake
  - role: user
    permission:
      check: {}
      set:
        profile_id: x-hasura-User-Id
      columns:
        - user_snowflake
select_permissions:
  - role: api-user
    permission:
      columns:
        - created_at
        - id
        - profile_id
        - updated_at
        - user_snowflake
      filter:
        profile:
          users:
            circle:
              api_keys:
                _and:
                  - hash:
                      _eq: X-Hasura-Api-Key-Hash
                  - read_discord:
                      _eq: true
                  - read_member_profiles:
                      _eq: true
  - role: discord-bot
    permission:
      columns:
        - id
        - profile_id
        - user_snowflake
        - created_at
        - updated_at
      filter: {}
  - role: user
    permission:
      columns:
        - created_at
        - id
        - profile_id
        - updated_at
        - user_snowflake
      filter:
        profile:
          id:
            _eq: X-Hasura-User-Id
update_permissions:
  - role: discord-bot
    permission:
      columns:
        - profile_id
        - user_snowflake
      filter: {}
      check: null
  - role: user
    permission:
      columns:
        - user_snowflake
      filter:
        profile:
          id:
            _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: discord-bot
    permission:
      backend_only: false
      filter: {}
  - role: user
    permission:
      backend_only: false
      filter:
        profile:
          id:
            _eq: X-Hasura-User-Id
event_triggers:
  - name: discordUserLinked
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
