table:
  name: emails
  schema: public
object_relationships:
  - name: profile
    using:
      foreign_key_constraint_on: profile_id
select_permissions:
  - role: user
    permission:
      columns:
        - email
        - primary
        - verified_at
      filter:
        profile_id:
          _eq: X-Hasura-User-Id
    comment: ""
event_triggers:
  - name: updateProfileRepScore_emails
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=updateProfileRepScore'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 0 3 * * *
      timeout: 60
