table:
  name: link_tx
  schema: public
object_relationships:
  - name: holder_profile
    using:
      manual_configuration:
        column_mapping:
          holder: address
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
  - name: target_profile
    using:
      manual_configuration:
        column_mapping:
          target: address
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
select_permissions:
  - role: anon
    permission:
      columns:
        - buy
        - eth_amount
        - protocol_fee_amount
        - link_amount
        - target_fee_amount
        - supply
        - created_at
        - target
        - holder
        - tx_hash
      filter: {}
      limit: 100
    comment: ''
  - role: user
    permission:
      columns:
        - buy
        - eth_amount
        - protocol_fee_amount
        - link_amount
        - target_fee_amount
        - supply
        - created_at
        - target
        - holder
        - tx_hash
      filter: {}
      limit: 1000
    comment: ''
event_triggers:
  - name: linkTxInteractionEvent
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 360
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=linkTxInteractionEvent'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 45 4 * * *
      timeout: 60
  - name: linkTxNotification
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=linkTxNotification'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 15 5 * * *
      timeout: 60
