table:
  name: contributions
  schema: public
object_relationships:
  - name: activity
    using:
      manual_configuration:
        column_mapping:
          id: contribution_id
        insertion_order: null
        remote_table:
          name: activities
          schema: public
  - name: big_question
    using:
      foreign_key_constraint_on: big_question_id
  - name: circle
    using:
      foreign_key_constraint_on: circle_id
  - name: created_with_api_key
    using:
      foreign_key_constraint_on: created_with_api_key_hash
  - name: profile
    using:
      manual_configuration:
        column_mapping:
          profile_id: id
        insertion_order: null
        remote_table:
          name: profiles
          schema: public
  - name: profile_public
    using:
      manual_configuration:
        column_mapping:
          profile_id: id
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: private_stream_visibility
    using:
      manual_configuration:
        column_mapping:
          profile_id: view_profile_id
        insertion_order: null
        remote_table:
          name: private_stream_visibility
          schema: public
insert_permissions:
  - role: api-user
    permission:
      check:
        circle:
          api_keys:
            _and:
              - hash:
                  _eq: X-Hasura-Api-Key-Hash
              - create_contributions:
                  _eq: true
      set:
        circle_id: X-Hasura-Circle-Id
        created_with_api_key_hash: x-hasura-Api-Key-Hash
      columns:
        - description
        - profile_id
        - user_id
  - role: user
    permission:
      check:
        _and:
          - _or:
              - user_id:
                  _is_null: true
              - user:
                  profile:
                    id:
                      _eq: X-Hasura-User-Id
          - _or:
              - circle:
                  users:
                    profile:
                      id:
                        _eq: X-Hasura-User-Id
              - _and:
                  - circle_id:
                      _is_null: true
                  - _or:
                      - private_stream:
                          _eq: true
                      - _and:
                          - private_stream:
                              _eq: false
                          - big_question:
                              publish_at:
                                _lte: now()
                          - big_question:
                              expire_at:
                                _gte: now()
      set:
        profile_id: x-hasura-User-Id
      columns:
        - big_question_id
        - circle_id
        - description
        - private_stream
        - user_id
select_permissions:
  - role: api-user
    permission:
      columns:
        - circle_id
        - created_at
        - description
        - id
        - profile_id
        - updated_at
        - user_id
      filter:
        _and:
          - circle:
              api_keys:
                _and:
                  - hash:
                      _eq: X-Hasura-Api-Key-Hash
                  - read_contributions:
                      _eq: true
          - deleted_at:
              _is_null: true
  - role: user
    permission:
      columns:
        - big_question_id
        - circle_id
        - created_at
        - created_with_api_key_hash
        - description
        - id
        - private_stream
        - profile_id
        - updated_at
        - user_id
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - _or:
              - profile_id:
                  _eq: X-Hasura-User-Id
              - circle:
                  organization:
                    members:
                      _and:
                        - profile_id:
                            _eq: X-Hasura-User-Id
                        - deleted_at:
                            _is_null: true
              - _and:
                  - private_stream:
                      _eq: true
                  - private_stream_visibility:
                      profile_id:
                        _eq: X-Hasura-User-Id
              - _and:
                  - big_question_id:
                      _is_null: false
                    private_stream:
                      _eq: false
      allow_aggregations: true
event_triggers:
  - name: activityContributionInsert
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=activityHandler'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 0 2 * * *
      timeout: 60
  - name: createContributionInteractionEvent
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=createContributionInteractionEvent'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 15 2 * * *
      timeout: 60
  - name: createNotificationPosts
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - deleted_at
          - description
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=createNotificationPosts'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 30 2 * * *
      timeout: 60
