table:
  name: farcaster_accounts
  schema: public
object_relationships:
  - name: profile_public
    using:
      foreign_key_constraint_on: profile_id
select_permissions:
  - role: anon
    permission:
      columns:
        - bio_text
        - created_at
        - custody_address
        - fid
        - followers_count
        - following_count
        - name
        - pfp_url
        - profile_id
        - updated_at
        - username
      filter: {}
      limit: 1
    comment: ""
  - role: api-user
    permission:
      columns:
        - fid
        - profile_id
        - followers_count
        - following_count
        - bio_text
        - custody_address
        - name
        - pfp_url
        - username
        - created_at
        - updated_at
      filter: {}
      limit: 1
    comment: ""
  - role: user
    permission:
      columns:
        - bio_text
        - created_at
        - custody_address
        - fid
        - followers_count
        - following_count
        - name
        - pfp_url
        - profile_id
        - updated_at
        - username
      filter: {}
      limit: 1
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        profile_id:
          _eq: X-Hasura-User-Id
    comment: ""
event_triggers:
  - name: updateProfileRepScore_farcaster
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=updateProfileRepScore'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 0 4 * * *
      timeout: 60
