table:
  name: enriched_casts
  schema: public
object_relationships:
  - name: activity
    using:
      foreign_key_constraint_on:
        column: cast_id
        table:
          name: activities
          schema: public
  - name: farcaster_profile
    using:
      manual_configuration:
        column_mapping:
          fid: fid
        insertion_order: null
        remote_table:
          name: profile_with_addresses
          schema: farcaster
  - name: fids
    using:
      manual_configuration:
        column_mapping:
          fid: fid
        insertion_order: null
        remote_table:
          name: fids
          schema: farcaster
  - name: profile_public
    using:
      manual_configuration:
        column_mapping:
          profile_id: id
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
array_relationships:
  - name: reactions
    using:
      manual_configuration:
        column_mapping:
          hash: target_hash
        insertion_order: null
        remote_table:
          name: reactions
          schema: farcaster
  - name: replies
    using:
      manual_configuration:
        column_mapping:
          hash: parent_hash
        insertion_order: null
        remote_table:
          name: casts
          schema: farcaster
select_permissions:
  - role: anon
    permission:
      columns:
        - mentions
        - mentions_positions
        - fid
        - id
        - parent_fid
        - profile_id
        - hash
        - parent_hash
        - root_parent_hash
        - embeds
        - parent_url
        - root_parent_url
        - text
        - created_at
        - deleted_at
        - timestamp
        - updated_at
      filter: {}
      limit: 100
    comment: ''
  - role: user
    permission:
      columns:
        - mentions
        - mentions_positions
        - fid
        - id
        - parent_fid
        - profile_id
        - hash
        - parent_hash
        - root_parent_hash
        - embeds
        - parent_url
        - root_parent_url
        - text
        - created_at
        - deleted_at
        - timestamp
        - updated_at
      filter: {}
      limit: 1
    comment: ''
event_triggers:
  - name: activityEnrichedCastInsert
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: '15 3 * * *'
      timeout: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=activityHandler'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
  - name: createEnrichedCastEmbedding
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=createEnrichedCastEmbedding'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 336
      paused: false
      schedule: '30 3 * * *'
      timeout: 60
