table:
  name: cosouls
  schema: public
object_relationships:
  - name: address_data_fetches
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: address_data_fetches
          schema: public
  - name: profile
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: profiles
          schema: public
  - name: profile_public
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
array_relationships:
  - name: held_links
    using:
      manual_configuration:
        column_mapping:
          address: holder
        insertion_order: null
        remote_table:
          name: link_holders
          schema: public
  - name: link_holders
    using:
      manual_configuration:
        column_mapping:
          address: target
        insertion_order: null
        remote_table:
          name: link_holders
          schema: public
  - name: poaps
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: poap_holders
          schema: public
select_permissions:
  - role: anon
    permission:
      columns:
        - address
        - checked_at
        - created_at
        - created_tx_hash
        - id
        - pgive
        - synced_at
        - token_id
        - updated_at
      filter: {}
      limit: 1
    comment: ''
  - role: user
    permission:
      columns:
        - address
        - created_at
        - created_tx_hash
        - id
        - pgive
        - synced_at
        - token_id
        - updated_at
      filter: {}
event_triggers:
  - name: updatePGIVERepScore
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=updatePGIVERepScore'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: '45 2 * * *'
      timeout: 60
