table:
  name: profiles
  schema: public
object_relationships:
  - name: address_data_fetches
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: address_data_fetches
          schema: public
  - name: cosoul
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: cosouls
          schema: public
  - name: farcaster_account
    using:
      manual_configuration:
        column_mapping:
          id: profile_id
        insertion_order: null
        remote_table:
          name: farcaster_accounts
          schema: public
  - name: profile_skills
    using:
      manual_configuration:
        column_mapping:
          id: profile_id
        insertion_order: null
        remote_table:
          name: profile_skills
          schema: public
  - name: reputation_score
    using:
      manual_configuration:
        column_mapping:
          id: profile_id
        insertion_order: null
        remote_table:
          name: reputation_scores
          schema: public
  - name: user
    using:
      foreign_key_constraint_on:
        column: profile_id
        table:
          name: users
          schema: discord
array_relationships:
  - name: claims
    using:
      manual_configuration:
        column_mapping:
          id: profile_id
        insertion_order: null
        remote_table:
          name: claims
          schema: public
  - name: colinks_gives_received
    using:
      foreign_key_constraint_on:
        column: target_profile_id
        table:
          name: colinks_gives
          schema: public
  - name: colinks_gives_sent
    using:
      manual_configuration:
        column_mapping:
          id: profile_id
        insertion_order: null
        remote_table:
          name: colinks_gives
          schema: public
  - name: distributions
    using:
      foreign_key_constraint_on:
        column: created_by
        table:
          name: distributions
          schema: public
  - name: emails
    using:
      foreign_key_constraint_on:
        column: profile_id
        table:
          name: emails
          schema: public
  - name: invite_codes
    using:
      manual_configuration:
        column_mapping:
          id: inviter_id
        insertion_order: null
        remote_table:
          name: invite_codes
          schema: public
  - name: nft_holdings
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: nft_holdings
          schema: public
  - name: nominees
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: nominees
          schema: public
  - name: org_members
    using:
      foreign_key_constraint_on:
        column: profile_id
        table:
          name: org_members
          schema: public
  - name: profile_flags
    using:
      foreign_key_constraint_on:
        column: profile_id
        table:
          name: profile_flags
          schema: public
  - name: token_balances
    using:
      manual_configuration:
        column_mapping:
          address: address
        insertion_order: null
        remote_table:
          name: token_balances
          schema: public
  - name: users
    using:
      foreign_key_constraint_on:
        column: profile_id
        table:
          name: users
          schema: public
  - name: vault_transactions
    using:
      foreign_key_constraint_on:
        column: created_by
        table:
          name: vault_transactions
          schema: public
  - name: vaults
    using:
      foreign_key_constraint_on:
        column: created_by
        table:
          name: vaults
          schema: public
select_permissions:
  - role: api-user
    permission:
      columns:
        - address
        - avatar
        - background
        - bio
        - created_at
        - discord_username
        - github_username
        - id
        - medium_username
        - name
        - skills
        - telegram_username
        - tos_agreed_at
        - twitter_username
        - updated_at
        - website
      filter:
        users:
          circle:
            api_keys:
              _and:
                - hash:
                    _eq: X-Hasura-Api-Key-Hash
                - read_member_profiles:
                    _eq: true
      limit: 50
  - role: discord-bot
    permission:
      columns:
        - id
        - name
        - address
      filter: {}
  - role: user
    permission:
      columns:
        - address
        - app_emails
        - avatar
        - background
        - bio
        - colinks_notification_emails
        - colinks_product_emails
        - created_at
        - description
        - discord_username
        - github_username
        - id
        - invite_code
        - invite_code_redeemed_at
        - invite_code_requested_at
        - invite_code_sent_at
        - invited_by
        - last_read_notification_id
        - links
        - links_held
        - medium_username
        - name
        - product_emails
        - skills
        - telegram_username
        - tos_agreed_at
        - twitter_username
        - updated_at
        - website
      filter:
        _or:
          - users:
              circle:
                organization:
                  members:
                    _and:
                      - deleted_at:
                          _is_null: true
                      - profile_id:
                          _eq: X-Hasura-User-Id
          - nominees:
              circle:
                organization:
                  members:
                    _and:
                      - deleted_at:
                          _is_null: true
                      - profile_id:
                          _eq: X-Hasura-User-Id
          - id:
              _eq: X-Hasura-User-Id
          - org_members:
              _and:
                - deleted_at:
                    _is_null: true
                - organization:
                    members:
                      _and:
                        - deleted_at:
                            _is_null: true
                        - profile_id:
                            _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - app_emails
        - avatar
        - background
        - bio
        - colinks_notification_emails
        - colinks_product_emails
        - description
        - discord_username
        - github_username
        - invite_code_redeemed_at
        - last_read_notification_id
        - medium_username
        - product_emails
        - skills
        - telegram_username
        - twitter_username
        - website
      filter:
        id:
          _eq: X-Hasura-User-Id
      check: null
      set:
        id: X-Hasura-User-Id
event_triggers:
  - name: connectFarcaster
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=connectFarcaster'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: '15 8 * * *'
      timeout: 60
  - name: updateDescriptionEmbedding
    definition:
      enable_manual: true
      insert:
        columns: '*'
      update:
        columns:
          - description
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=updateDescriptionEmbedding'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: '30 8 * * *'
      timeout: 60
