table:
  name: contributions
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circle_id
  - name: created_with_api_key
    using:
      foreign_key_constraint_on: created_with_api_key_hash
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: api-user
    permission:
      check:
        circle:
          api_keys:
            _and:
              - hash:
                  _eq: X-Hasura-Api-Key-Hash
              - create_contributions:
                  _eq: true
      set:
        circle_id: X-Hasura-Circle-Id
        created_with_api_key_hash: x-hasura-Api-Key-Hash
      columns:
        - description
        - user_id
  - role: user
    permission:
      check:
        _and:
          - _or:
              - user_id:
                  _is_null: true
              - user:
                  profile:
                    id:
                      _eq: X-Hasura-User-Id
          - _or:
              - circle:
                  users:
                    profile:
                      id:
                        _eq: X-Hasura-User-Id
              - _and:
                  - circle_id:
                      _is_null: true
                  - private_stream:
                      _eq: true
      set:
        profile_id: x-hasura-User-Id
      columns:
        - circle_id
        - description
        - private_stream
        - user_id
select_permissions:
  - role: api-user
    permission:
      columns:
        - circle_id
        - created_at
        - description
        - id
        - updated_at
        - user_id
      filter:
        _and:
          - circle:
              api_keys:
                _and:
                  - hash:
                      _eq: X-Hasura-Api-Key-Hash
                  - read_contributions:
                      _eq: true
          - deleted_at:
              _is_null: true
  - role: user
    permission:
      columns:
        - circle_id
        - created_at
        - created_with_api_key_hash
        - description
        - id
        - private_stream
        - updated_at
        - user_id
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - _or:
              - profile_id:
                  _eq: X-Hasura-User-Id
              - circle:
                  organization:
                    members:
                      _and:
                        - profile_id:
                            _eq: X-Hasura-User-Id
                        - deleted_at:
                            _is_null: true
      allow_aggregations: true
event_triggers:
  - name: activityContributionInsert
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=activityHandler'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: createContributionInteractionEvent
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=createContributionInteractionEvent'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
