table:
  name: users
  schema: public
object_relationships:
  - name: circle
    using:
      foreign_key_constraint_on: circle_id
  - name: profile
    using:
      foreign_key_constraint_on: address
  - name: user_private
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: user_private
          schema: public
array_relationships:
  - name: burns
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: burns
          schema: public
  - name: circle_api_keys
    using:
      foreign_key_constraint_on:
        column: created_by
        table:
          name: circle_api_keys
          schema: public
  - name: contributions
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: contributions
          schema: public
  - name: pending_received_gifts
    using:
      foreign_key_constraint_on:
        column: recipient_id
        table:
          name: pending_token_gifts
          schema: public
  - name: pending_sent_gifts
    using:
      foreign_key_constraint_on:
        column: sender_id
        table:
          name: pending_token_gifts
          schema: public
  - name: received_gifts
    using:
      foreign_key_constraint_on:
        column: recipient_id
        table:
          name: token_gifts
          schema: public
  - name: sent_gifts
    using:
      foreign_key_constraint_on:
        column: sender_id
        table:
          name: token_gifts
          schema: public
  - name: teammates
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: teammates
          schema: public
  - name: vouches
    using:
      foreign_key_constraint_on:
        column: voucher_id
        table:
          name: vouches
          schema: public
select_permissions:
  - role: api-user
    permission:
      columns:
        - bio
        - circle_id
        - created_at
        - fixed_non_receiver
        - give_token_received
        - give_token_remaining
        - id
        - name
        - non_giver
        - non_receiver
        - starting_tokens
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - circle:
              api_keys:
                _and:
                  - hash:
                      _eq: X-Hasura-Api-Key-Hash
                  - _or:
                      - read_pending_token_gifts:
                          _eq: true
                      - read_member_profiles:
                          _eq: true
      limit: 50
  - role: discord-bot
    permission:
      columns:
        - circle_id
        - role
      filter: {}
  - role: user
    permission:
      columns:
        - address
        - bio
        - circle_id
        - created_at
        - deleted_at
        - epoch_first_visit
        - fixed_non_receiver
        - give_token_received
        - give_token_remaining
        - id
        - name
        - non_giver
        - non_receiver
        - role
        - starting_tokens
        - updated_at
      filter:
        _and:
          - deleted_at:
              _is_null: true
          - circle:
              users:
                profile:
                  id:
                    _eq: X-Hasura-User-Id
event_triggers:
  - name: optOutDiscord
    definition:
      enable_manual: false
      update:
        columns:
          - non_giver
          - non_receiver
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=optOutDiscord'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
  - name: optOutDiscordBot
    definition:
      enable_manual: false
      update:
        columns:
          - non_giver
          - deleted_at
          - non_receiver
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: optOutTelegram
    definition:
      enable_manual: false
      update:
        columns:
          - non_giver
          - non_receiver
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=optOutTelegram'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
  - name: refundPendingGift
    definition:
      enable_manual: false
      update:
        columns:
          - non_giver
          - non_receiver
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=refundPendingGift'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
  - name: activityHandlerUserInsert
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?event=activityHandler'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: userAddedDiscordBot
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - deleted_at
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=userAddedDiscordBot'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
  - name: userRemovedDiscordBot
    definition:
      enable_manual: false
      update:
        columns:
          - deleted_at
    retry_conf:
      interval_sec: 3600
      num_retries: 5
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=userRemovedDiscordBot'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
