table:
  name: mutes
  schema: public
object_relationships:
  - name: profile
    using:
      manual_configuration:
        column_mapping:
          profile_id: id
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
  - name: target_profile
    using:
      manual_configuration:
        column_mapping:
          target_profile_id: id
        insertion_order: null
        remote_table:
          name: profiles_public
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        profile_id:
          _eq: X-Hasura-User-Id
      columns:
        - profile_id
        - target_profile_id
    comment: ""
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - profile_id
        - target_profile_id
      filter:
        _or:
          - profile_id:
              _eq: X-Hasura-User-Id
          - target_profile_id:
              _eq: X-Hasura-User-Id
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        profile_id:
          _eq: X-Hasura-User-Id
    comment: ""
event_triggers:
  - name: muteChanged
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_API_BASE_URL}}/event_triggers/eventManager?=muteChanged'
    headers:
      - name: verification_key
        value_from_env: HASURA_EVENT_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: true
      clear_older_than: 672
      paused: false
      schedule: 45 5 * * *
      timeout: 60
