-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."activities" add column "private_stream" boolean
--  null default 'false';
