-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."profiles" add column "points_balance" integer
--  not null default '0';
