-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- update "public"."profiles" set avatar = CONCAT('assets/static/avatars/',avatar)
-- where avatar not ilike 'assets/static/avatars/%' and avatar is not null;
