#!/bin/bash
set -e

echo "Copying env..."
cp .env.buildkite.example .env

echo "Building api server..."
git clone git@github.com:coordinape/coordinape-backend.git || true
cd coordinape-backend/
cp .env.example .env
docker-compose up -d
cd ..