#!/bin/bash

METADATA_DIR=./hasura/metadata/databases/default/tables

if [ -z "$CI" ]; then
  HASURA_ENV="--envfile ../.env"
else
  HASURA_ENV="--envfile ../.ci.env"
fi

# Uncomment event triggers
for file in "$METADATA_DIR"/public_*.yaml; do
  sed -i'.bak' -e "/event_triggers:/,$"' s/^#//g' "$file"
done

# Remove backup files generated by sed
find $METADATA_DIR -name '*.bak' | xargs rm

# Apply metadata to GraphQL Engine
yarn hasura $HASURA_ENV metadata apply
