#!/bin/bash

METADATA_DIR=./hasura/metadata/databases/default/tables

# Uncomment event triggers
for file in "$METADATA_DIR"/public_*.yaml; do
  sed -i'.bak' -e "/event_triggers:/,$"' s/^#//g' "$file"
done

# Remove backup files generated by sed
find $METADATA_DIR -name '*.bak' | xargs rm

# Apply metadata to GraphQL Engine
yarn hasura metadata apply
