export const EMAIL_SCORE_MAX = 100;
export const EMAIL_SCORE_PER_DOMAIN = 50;

export const COLINKS_POST_SCORE = 3;
export const COLINKS_POST_REPLY_SCORE = 2;
export const COLINKS_POST_REACTION_SCORE = 1;
export const COLINKS_POST_SCORE_MAX = 1000;

export const COLINK_HOLDER_VALUE = 20;
export const COLINK_HOLDING_VALUE = 10;
export const COLINKS_SCORE_MAX = 4000;
export const TWITTER_SCORE_BASE = 100;
export const TWITTER_FOLLOWER_SCORE_VALUE = 0.1;
export const TWITTER_SCORE_MAX = 400;
export const POAP_HOLDING_VALUE = 5;
export const POAP_SCORE_MAX = 200;
export const GITHUB_SCORE_BASE = 100;
export const GITHUB_SCORE_MAX = 400;
export const INVITE_SCORE_MAX = 400;
export const INVITE_SCORE_PER_INVITE_WITH_COSOUL = 40;
export const INVITE_SCORE_PER_INVITE_WITH_NO_COSOUL = 10;
export const LINKEDIN_SCORE_BASE = 100;
export const LINKEDIN_SCORE_VERIFIED_EMAIL = 200;
export const LINKEDIN_SCORE_MAX = 300;
