export const EMAIL_SCORE_MAX = 100;
export const EMAIL_SCORE_PER_DOMAIN = 50;

export const COLINKS_ENGAGEMENT_POST_SCORE = 1;
export const COLINKS_ENGAGEMENT_POST_WITH_ANY_REPLIES_SCORE = 3;
export const COLINKS_ENGAGEMENT_POST_WITH_ANY_REACTIONS_SCORE = 1;
export const COLINKS_ENGAGEMENT_SCORE_MAX = 3000;

export const COLINK_LINK_HOLDER_VALUE = 40;
export const COLINK_LINK_HOLDING_VALUE = 10;
export const COLINKS_LINK_SCORE_MAX = 7000;

export const COLINKS_INVITE_SCORE_MAX = 5000;
export const COLINKS_INVITE_SCORE_PER_INVITE_BASE = 50;
export const COLINKS_INVITE_SCORE_PER_INVITEE_REPUTATION_BONUS_MAX = 150;

export const TWITTER_SCORE_BASE = 100;
export const TWITTER_FOLLOWER_SCORE_VALUE = 0.1;
export const TWITTER_SCORE_MAX = 300;
export const POAP_HOLDING_VALUE = 50;
export const POAP_SCORE_MAX = 500;
export const GITHUB_SCORE_BASE = 100;
export const GITHUB_SCORE_MAX = 300;
export const LINKEDIN_SCORE_BASE = 100;
export const LINKEDIN_SCORE_VERIFIED_EMAIL = 200;
export const LINKEDIN_SCORE_MAX = 300;

export const PGIVE_MAX_SCORE = 3500;

export const CAT_COLINKS_MAX_SCORE =
  COLINKS_ENGAGEMENT_SCORE_MAX +
  COLINKS_LINK_SCORE_MAX +
  COLINKS_INVITE_SCORE_MAX;
export const CAT_WEB2_MAX_SCORE =
  TWITTER_SCORE_MAX + GITHUB_SCORE_MAX + LINKEDIN_SCORE_MAX + EMAIL_SCORE_MAX;
export const CAT_WEB3_MAX_SCORE = POAP_SCORE_MAX;
export const CAT_COORDINAPE_ECOSYSTEM_MAX_SCORE = PGIVE_MAX_SCORE;

export const MAX_REP_SCORE =
  CAT_COLINKS_MAX_SCORE +
  CAT_WEB2_MAX_SCORE +
  CAT_WEB3_MAX_SCORE +
  CAT_COORDINAPE_ECOSYSTEM_MAX_SCORE;
