-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."circle_integrations" add column "updated_at" timestamptz
--  null;
