-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."epoches" add column "gives_receiver_base" numeric
--  not null default '0';
