-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."big_questions" add column "css_background_position" text
--  null;
